// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package template

import (
	"context"

	"github.com/pl3lee/uwplan/api/internal/domain/template"
	mock "github.com/stretchr/testify/mock"
)

// NewTemplateRepositoryMock creates a new instance of TemplateRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTemplateRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TemplateRepositoryMock {
	mock := &TemplateRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TemplateRepositoryMock is an autogenerated mock type for the TemplateRepository type
type TemplateRepositoryMock struct {
	mock.Mock
}

type TemplateRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TemplateRepositoryMock) EXPECT() *TemplateRepositoryMock_Expecter {
	return &TemplateRepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type TemplateRepositoryMock
func (_mock *TemplateRepositoryMock) Create(context1 context.Context, draft template.Draft) (template.Template, error) {
	ret := _mock.Called(context1, draft)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 template.Template
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, template.Draft) (template.Template, error)); ok {
		return returnFunc(context1, draft)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, template.Draft) template.Template); ok {
		r0 = returnFunc(context1, draft)
	} else {
		r0 = ret.Get(0).(template.Template)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, template.Draft) error); ok {
		r1 = returnFunc(context1, draft)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TemplateRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TemplateRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - draft template.Draft
func (_e *TemplateRepositoryMock_Expecter) Create(context1 interface{}, draft interface{}) *TemplateRepositoryMock_Create_Call {
	return &TemplateRepositoryMock_Create_Call{Call: _e.mock.On("Create", context1, draft)}
}

func (_c *TemplateRepositoryMock_Create_Call) Run(run func(context1 context.Context, draft template.Draft)) *TemplateRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 template.Draft
		if args[1] != nil {
			arg1 = args[1].(template.Draft)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TemplateRepositoryMock_Create_Call) Return(template1 template.Template, err error) *TemplateRepositoryMock_Create_Call {
	_c.Call.Return(template1, err)
	return _c
}

func (_c *TemplateRepositoryMock_Create_Call) RunAndReturn(run func(context1 context.Context, draft template.Draft) (template.Template, error)) *TemplateRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type TemplateRepositoryMock
func (_mock *TemplateRepositoryMock) Delete(context1 context.Context, reference template.Reference) error {
	ret := _mock.Called(context1, reference)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, template.Reference) error); ok {
		r0 = returnFunc(context1, reference)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TemplateRepositoryMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TemplateRepositoryMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - reference template.Reference
func (_e *TemplateRepositoryMock_Expecter) Delete(context1 interface{}, reference interface{}) *TemplateRepositoryMock_Delete_Call {
	return &TemplateRepositoryMock_Delete_Call{Call: _e.mock.On("Delete", context1, reference)}
}

func (_c *TemplateRepositoryMock_Delete_Call) Run(run func(context1 context.Context, reference template.Reference)) *TemplateRepositoryMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 template.Reference
		if args[1] != nil {
			arg1 = args[1].(template.Reference)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TemplateRepositoryMock_Delete_Call) Return(err error) *TemplateRepositoryMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TemplateRepositoryMock_Delete_Call) RunAndReturn(run func(context1 context.Context, reference template.Reference) error) *TemplateRepositoryMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type TemplateRepositoryMock
func (_mock *TemplateRepositoryMock) Get(context1 context.Context, reference template.Reference) (template.Definition, error) {
	ret := _mock.Called(context1, reference)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 template.Definition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, template.Reference) (template.Definition, error)); ok {
		return returnFunc(context1, reference)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, template.Reference) template.Definition); ok {
		r0 = returnFunc(context1, reference)
	} else {
		r0 = ret.Get(0).(template.Definition)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, template.Reference) error); ok {
		r1 = returnFunc(context1, reference)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TemplateRepositoryMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TemplateRepositoryMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - reference template.Reference
func (_e *TemplateRepositoryMock_Expecter) Get(context1 interface{}, reference interface{}) *TemplateRepositoryMock_Get_Call {
	return &TemplateRepositoryMock_Get_Call{Call: _e.mock.On("Get", context1, reference)}
}

func (_c *TemplateRepositoryMock_Get_Call) Run(run func(context1 context.Context, reference template.Reference)) *TemplateRepositoryMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 template.Reference
		if args[1] != nil {
			arg1 = args[1].(template.Reference)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TemplateRepositoryMock_Get_Call) Return(definition template.Definition, err error) *TemplateRepositoryMock_Get_Call {
	_c.Call.Return(definition, err)
	return _c
}

func (_c *TemplateRepositoryMock_Get_Call) RunAndReturn(run func(context1 context.Context, reference template.Reference) (template.Definition, error)) *TemplateRepositoryMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type TemplateRepositoryMock
func (_mock *TemplateRepositoryMock) List(context1 context.Context, list template.List) ([]template.Template, error) {
	ret := _mock.Called(context1, list)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []template.Template
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, template.List) ([]template.Template, error)); ok {
		return returnFunc(context1, list)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, template.List) []template.Template); ok {
		r0 = returnFunc(context1, list)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]template.Template)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, template.List) error); ok {
		r1 = returnFunc(context1, list)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TemplateRepositoryMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TemplateRepositoryMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - list template.List
func (_e *TemplateRepositoryMock_Expecter) List(context1 interface{}, list interface{}) *TemplateRepositoryMock_List_Call {
	return &TemplateRepositoryMock_List_Call{Call: _e.mock.On("List", context1, list)}
}

func (_c *TemplateRepositoryMock_List_Call) Run(run func(context1 context.Context, list template.List)) *TemplateRepositoryMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 template.List
		if args[1] != nil {
			arg1 = args[1].(template.List)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TemplateRepositoryMock_List_Call) Return(templates []template.Template, err error) *TemplateRepositoryMock_List_Call {
	_c.Call.Return(templates, err)
	return _c
}

func (_c *TemplateRepositoryMock_List_Call) RunAndReturn(run func(context1 context.Context, list template.List) ([]template.Template, error)) *TemplateRepositoryMock_List_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type TemplateRepositoryMock
func (_mock *TemplateRepositoryMock) Rename(context1 context.Context, rename template.Rename) error {
	ret := _mock.Called(context1, rename)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, template.Rename) error); ok {
		r0 = returnFunc(context1, rename)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TemplateRepositoryMock_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type TemplateRepositoryMock_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - context1 context.Context
//   - rename template.Rename
func (_e *TemplateRepositoryMock_Expecter) Rename(context1 interface{}, rename interface{}) *TemplateRepositoryMock_Rename_Call {
	return &TemplateRepositoryMock_Rename_Call{Call: _e.mock.On("Rename", context1, rename)}
}

func (_c *TemplateRepositoryMock_Rename_Call) Run(run func(context1 context.Context, rename template.Rename)) *TemplateRepositoryMock_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 template.Rename
		if args[1] != nil {
			arg1 = args[1].(template.Rename)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TemplateRepositoryMock_Rename_Call) Return(err error) *TemplateRepositoryMock_Rename_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TemplateRepositoryMock_Rename_Call) RunAndReturn(run func(context1 context.Context, rename template.Rename) error) *TemplateRepositoryMock_Rename_Call {
	_c.Call.Return(run)
	return _c
}
