// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package schedule

import (
	"context"

	"github.com/pl3lee/uwplan/api/internal/domain/schedule"
	"github.com/pl3lee/uwplan/api/internal/domain/term"
	"github.com/pl3lee/uwplan/api/internal/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// NewScheduleRepositoryMock creates a new instance of ScheduleRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScheduleRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScheduleRepositoryMock {
	mock := &ScheduleRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ScheduleRepositoryMock is an autogenerated mock type for the ScheduleRepository type
type ScheduleRepositoryMock struct {
	mock.Mock
}

type ScheduleRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ScheduleRepositoryMock) EXPECT() *ScheduleRepositoryMock_Expecter {
	return &ScheduleRepositoryMock_Expecter{mock: &_m.Mock}
}

// Assign provides a mock function for the type ScheduleRepositoryMock
func (_mock *ScheduleRepositoryMock) Assign(context1 context.Context, assign schedule.Assign) error {
	ret := _mock.Called(context1, assign)

	if len(ret) == 0 {
		panic("no return value specified for Assign")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, schedule.Assign) error); ok {
		r0 = returnFunc(context1, assign)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ScheduleRepositoryMock_Assign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assign'
type ScheduleRepositoryMock_Assign_Call struct {
	*mock.Call
}

// Assign is a helper method to define mock.On call
//   - context1 context.Context
//   - assign schedule.Assign
func (_e *ScheduleRepositoryMock_Expecter) Assign(context1 interface{}, assign interface{}) *ScheduleRepositoryMock_Assign_Call {
	return &ScheduleRepositoryMock_Assign_Call{Call: _e.mock.On("Assign", context1, assign)}
}

func (_c *ScheduleRepositoryMock_Assign_Call) Run(run func(context1 context.Context, assign schedule.Assign)) *ScheduleRepositoryMock_Assign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 schedule.Assign
		if args[1] != nil {
			arg1 = args[1].(schedule.Assign)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScheduleRepositoryMock_Assign_Call) Return(err error) *ScheduleRepositoryMock_Assign_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ScheduleRepositoryMock_Assign_Call) RunAndReturn(run func(context1 context.Context, assign schedule.Assign) error) *ScheduleRepositoryMock_Assign_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeTermRange provides a mock function for the type ScheduleRepositoryMock
func (_mock *ScheduleRepositoryMock) ChangeTermRange(context1 context.Context, termRangeChange schedule.TermRangeChange) error {
	ret := _mock.Called(context1, termRangeChange)

	if len(ret) == 0 {
		panic("no return value specified for ChangeTermRange")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, schedule.TermRangeChange) error); ok {
		r0 = returnFunc(context1, termRangeChange)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ScheduleRepositoryMock_ChangeTermRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeTermRange'
type ScheduleRepositoryMock_ChangeTermRange_Call struct {
	*mock.Call
}

// ChangeTermRange is a helper method to define mock.On call
//   - context1 context.Context
//   - termRangeChange schedule.TermRangeChange
func (_e *ScheduleRepositoryMock_Expecter) ChangeTermRange(context1 interface{}, termRangeChange interface{}) *ScheduleRepositoryMock_ChangeTermRange_Call {
	return &ScheduleRepositoryMock_ChangeTermRange_Call{Call: _e.mock.On("ChangeTermRange", context1, termRangeChange)}
}

func (_c *ScheduleRepositoryMock_ChangeTermRange_Call) Run(run func(context1 context.Context, termRangeChange schedule.TermRangeChange)) *ScheduleRepositoryMock_ChangeTermRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 schedule.TermRangeChange
		if args[1] != nil {
			arg1 = args[1].(schedule.TermRangeChange)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScheduleRepositoryMock_ChangeTermRange_Call) Return(err error) *ScheduleRepositoryMock_ChangeTermRange_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ScheduleRepositoryMock_ChangeTermRange_Call) RunAndReturn(run func(context1 context.Context, termRangeChange schedule.TermRangeChange) error) *ScheduleRepositoryMock_ChangeTermRange_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type ScheduleRepositoryMock
func (_mock *ScheduleRepositoryMock) Create(context1 context.Context, create schedule.Create) (schedule.Schedule, error) {
	ret := _mock.Called(context1, create)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 schedule.Schedule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, schedule.Create) (schedule.Schedule, error)); ok {
		return returnFunc(context1, create)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, schedule.Create) schedule.Schedule); ok {
		r0 = returnFunc(context1, create)
	} else {
		r0 = ret.Get(0).(schedule.Schedule)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, schedule.Create) error); ok {
		r1 = returnFunc(context1, create)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ScheduleRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ScheduleRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - create schedule.Create
func (_e *ScheduleRepositoryMock_Expecter) Create(context1 interface{}, create interface{}) *ScheduleRepositoryMock_Create_Call {
	return &ScheduleRepositoryMock_Create_Call{Call: _e.mock.On("Create", context1, create)}
}

func (_c *ScheduleRepositoryMock_Create_Call) Run(run func(context1 context.Context, create schedule.Create)) *ScheduleRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 schedule.Create
		if args[1] != nil {
			arg1 = args[1].(schedule.Create)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScheduleRepositoryMock_Create_Call) Return(schedule1 schedule.Schedule, err error) *ScheduleRepositoryMock_Create_Call {
	_c.Call.Return(schedule1, err)
	return _c
}

func (_c *ScheduleRepositoryMock_Create_Call) RunAndReturn(run func(context1 context.Context, create schedule.Create) (schedule.Schedule, error)) *ScheduleRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ScheduleRepositoryMock
func (_mock *ScheduleRepositoryMock) Delete(context1 context.Context, reference schedule.Reference) error {
	ret := _mock.Called(context1, reference)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, schedule.Reference) error); ok {
		r0 = returnFunc(context1, reference)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ScheduleRepositoryMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ScheduleRepositoryMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - reference schedule.Reference
func (_e *ScheduleRepositoryMock_Expecter) Delete(context1 interface{}, reference interface{}) *ScheduleRepositoryMock_Delete_Call {
	return &ScheduleRepositoryMock_Delete_Call{Call: _e.mock.On("Delete", context1, reference)}
}

func (_c *ScheduleRepositoryMock_Delete_Call) Run(run func(context1 context.Context, reference schedule.Reference)) *ScheduleRepositoryMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 schedule.Reference
		if args[1] != nil {
			arg1 = args[1].(schedule.Reference)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScheduleRepositoryMock_Delete_Call) Return(err error) *ScheduleRepositoryMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ScheduleRepositoryMock_Delete_Call) RunAndReturn(run func(context1 context.Context, reference schedule.Reference) error) *ScheduleRepositoryMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetTermRange provides a mock function for the type ScheduleRepositoryMock
func (_mock *ScheduleRepositoryMock) GetTermRange(context1 context.Context, user1 user.User) (term.Range, error) {
	ret := _mock.Called(context1, user1)

	if len(ret) == 0 {
		panic("no return value specified for GetTermRange")
	}

	var r0 term.Range
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) (term.Range, error)); ok {
		return returnFunc(context1, user1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) term.Range); ok {
		r0 = returnFunc(context1, user1)
	} else {
		r0 = ret.Get(0).(term.Range)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.User) error); ok {
		r1 = returnFunc(context1, user1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ScheduleRepositoryMock_GetTermRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTermRange'
type ScheduleRepositoryMock_GetTermRange_Call struct {
	*mock.Call
}

// GetTermRange is a helper method to define mock.On call
//   - context1 context.Context
//   - user1 user.User
func (_e *ScheduleRepositoryMock_Expecter) GetTermRange(context1 interface{}, user1 interface{}) *ScheduleRepositoryMock_GetTermRange_Call {
	return &ScheduleRepositoryMock_GetTermRange_Call{Call: _e.mock.On("GetTermRange", context1, user1)}
}

func (_c *ScheduleRepositoryMock_GetTermRange_Call) Run(run func(context1 context.Context, user1 user.User)) *ScheduleRepositoryMock_GetTermRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.User
		if args[1] != nil {
			arg1 = args[1].(user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScheduleRepositoryMock_GetTermRange_Call) Return(rangeParam term.Range, err error) *ScheduleRepositoryMock_GetTermRange_Call {
	_c.Call.Return(rangeParam, err)
	return _c
}

func (_c *ScheduleRepositoryMock_GetTermRange_Call) RunAndReturn(run func(context1 context.Context, user1 user.User) (term.Range, error)) *ScheduleRepositoryMock_GetTermRange_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type ScheduleRepositoryMock
func (_mock *ScheduleRepositoryMock) List(context1 context.Context, user1 user.User) (schedule.Collection, error) {
	ret := _mock.Called(context1, user1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 schedule.Collection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) (schedule.Collection, error)); ok {
		return returnFunc(context1, user1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) schedule.Collection); ok {
		r0 = returnFunc(context1, user1)
	} else {
		r0 = ret.Get(0).(schedule.Collection)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.User) error); ok {
		r1 = returnFunc(context1, user1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ScheduleRepositoryMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ScheduleRepositoryMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - user1 user.User
func (_e *ScheduleRepositoryMock_Expecter) List(context1 interface{}, user1 interface{}) *ScheduleRepositoryMock_List_Call {
	return &ScheduleRepositoryMock_List_Call{Call: _e.mock.On("List", context1, user1)}
}

func (_c *ScheduleRepositoryMock_List_Call) Run(run func(context1 context.Context, user1 user.User)) *ScheduleRepositoryMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.User
		if args[1] != nil {
			arg1 = args[1].(user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScheduleRepositoryMock_List_Call) Return(collection schedule.Collection, err error) *ScheduleRepositoryMock_List_Call {
	_c.Call.Return(collection, err)
	return _c
}

func (_c *ScheduleRepositoryMock_List_Call) RunAndReturn(run func(context1 context.Context, user1 user.User) (schedule.Collection, error)) *ScheduleRepositoryMock_List_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveCourse provides a mock function for the type ScheduleRepositoryMock
func (_mock *ScheduleRepositoryMock) RemoveCourse(context1 context.Context, removeCourse schedule.RemoveCourse) error {
	ret := _mock.Called(context1, removeCourse)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCourse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, schedule.RemoveCourse) error); ok {
		r0 = returnFunc(context1, removeCourse)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ScheduleRepositoryMock_RemoveCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveCourse'
type ScheduleRepositoryMock_RemoveCourse_Call struct {
	*mock.Call
}

// RemoveCourse is a helper method to define mock.On call
//   - context1 context.Context
//   - removeCourse schedule.RemoveCourse
func (_e *ScheduleRepositoryMock_Expecter) RemoveCourse(context1 interface{}, removeCourse interface{}) *ScheduleRepositoryMock_RemoveCourse_Call {
	return &ScheduleRepositoryMock_RemoveCourse_Call{Call: _e.mock.On("RemoveCourse", context1, removeCourse)}
}

func (_c *ScheduleRepositoryMock_RemoveCourse_Call) Run(run func(context1 context.Context, removeCourse schedule.RemoveCourse)) *ScheduleRepositoryMock_RemoveCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 schedule.RemoveCourse
		if args[1] != nil {
			arg1 = args[1].(schedule.RemoveCourse)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScheduleRepositoryMock_RemoveCourse_Call) Return(err error) *ScheduleRepositoryMock_RemoveCourse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ScheduleRepositoryMock_RemoveCourse_Call) RunAndReturn(run func(context1 context.Context, removeCourse schedule.RemoveCourse) error) *ScheduleRepositoryMock_RemoveCourse_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type ScheduleRepositoryMock
func (_mock *ScheduleRepositoryMock) Rename(context1 context.Context, rename schedule.Rename) error {
	ret := _mock.Called(context1, rename)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, schedule.Rename) error); ok {
		r0 = returnFunc(context1, rename)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ScheduleRepositoryMock_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type ScheduleRepositoryMock_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - context1 context.Context
//   - rename schedule.Rename
func (_e *ScheduleRepositoryMock_Expecter) Rename(context1 interface{}, rename interface{}) *ScheduleRepositoryMock_Rename_Call {
	return &ScheduleRepositoryMock_Rename_Call{Call: _e.mock.On("Rename", context1, rename)}
}

func (_c *ScheduleRepositoryMock_Rename_Call) Run(run func(context1 context.Context, rename schedule.Rename)) *ScheduleRepositoryMock_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 schedule.Rename
		if args[1] != nil {
			arg1 = args[1].(schedule.Rename)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScheduleRepositoryMock_Rename_Call) Return(err error) *ScheduleRepositoryMock_Rename_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ScheduleRepositoryMock_Rename_Call) RunAndReturn(run func(context1 context.Context, rename schedule.Rename) error) *ScheduleRepositoryMock_Rename_Call {
	_c.Call.Return(run)
	return _c
}

// View provides a mock function for the type ScheduleRepositoryMock
func (_mock *ScheduleRepositoryMock) View(context1 context.Context, reference schedule.Reference) (schedule.View, error) {
	ret := _mock.Called(context1, reference)

	if len(ret) == 0 {
		panic("no return value specified for View")
	}

	var r0 schedule.View
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, schedule.Reference) (schedule.View, error)); ok {
		return returnFunc(context1, reference)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, schedule.Reference) schedule.View); ok {
		r0 = returnFunc(context1, reference)
	} else {
		r0 = ret.Get(0).(schedule.View)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, schedule.Reference) error); ok {
		r1 = returnFunc(context1, reference)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ScheduleRepositoryMock_View_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'View'
type ScheduleRepositoryMock_View_Call struct {
	*mock.Call
}

// View is a helper method to define mock.On call
//   - context1 context.Context
//   - reference schedule.Reference
func (_e *ScheduleRepositoryMock_Expecter) View(context1 interface{}, reference interface{}) *ScheduleRepositoryMock_View_Call {
	return &ScheduleRepositoryMock_View_Call{Call: _e.mock.On("View", context1, reference)}
}

func (_c *ScheduleRepositoryMock_View_Call) Run(run func(context1 context.Context, reference schedule.Reference)) *ScheduleRepositoryMock_View_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 schedule.Reference
		if args[1] != nil {
			arg1 = args[1].(schedule.Reference)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScheduleRepositoryMock_View_Call) Return(view schedule.View, err error) *ScheduleRepositoryMock_View_Call {
	_c.Call.Return(view, err)
	return _c
}

func (_c *ScheduleRepositoryMock_View_Call) RunAndReturn(run func(context1 context.Context, reference schedule.Reference) (schedule.View, error)) *ScheduleRepositoryMock_View_Call {
	_c.Call.Return(run)
	return _c
}
