// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"

	"github.com/pl3lee/uwplan/api/internal/domain/health"
	"github.com/pl3lee/uwplan/api/internal/domain/oauth"
	"github.com/pl3lee/uwplan/api/internal/domain/session"
	"github.com/pl3lee/uwplan/api/internal/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthServiceMock creates a new instance of AuthServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServiceMock {
	mock := &AuthServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthServiceMock is an autogenerated mock type for the AuthService type
type AuthServiceMock struct {
	mock.Mock
}

type AuthServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthServiceMock) EXPECT() *AuthServiceMock_Expecter {
	return &AuthServiceMock_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) Authenticate(context1 context.Context, credentials session.Credentials) (user.User, error) {
	ret := _mock.Called(context1, credentials)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.Credentials) (user.User, error)); ok {
		return returnFunc(context1, credentials)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.Credentials) user.User); ok {
		r0 = returnFunc(context1, credentials)
	} else {
		r0 = ret.Get(0).(user.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, session.Credentials) error); ok {
		r1 = returnFunc(context1, credentials)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthServiceMock_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type AuthServiceMock_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - context1 context.Context
//   - credentials session.Credentials
func (_e *AuthServiceMock_Expecter) Authenticate(context1 interface{}, credentials interface{}) *AuthServiceMock_Authenticate_Call {
	return &AuthServiceMock_Authenticate_Call{Call: _e.mock.On("Authenticate", context1, credentials)}
}

func (_c *AuthServiceMock_Authenticate_Call) Run(run func(context1 context.Context, credentials session.Credentials)) *AuthServiceMock_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 session.Credentials
		if args[1] != nil {
			arg1 = args[1].(session.Credentials)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthServiceMock_Authenticate_Call) Return(user1 user.User, err error) *AuthServiceMock_Authenticate_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *AuthServiceMock_Authenticate_Call) RunAndReturn(run func(context1 context.Context, credentials session.Credentials) (user.User, error)) *AuthServiceMock_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) Logout(context1 context.Context, credentials session.Credentials) error {
	ret := _mock.Called(context1, credentials)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.Credentials) error); ok {
		r0 = returnFunc(context1, credentials)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthServiceMock_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AuthServiceMock_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - context1 context.Context
//   - credentials session.Credentials
func (_e *AuthServiceMock_Expecter) Logout(context1 interface{}, credentials interface{}) *AuthServiceMock_Logout_Call {
	return &AuthServiceMock_Logout_Call{Call: _e.mock.On("Logout", context1, credentials)}
}

func (_c *AuthServiceMock_Logout_Call) Run(run func(context1 context.Context, credentials session.Credentials)) *AuthServiceMock_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 session.Credentials
		if args[1] != nil {
			arg1 = args[1].(session.Credentials)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthServiceMock_Logout_Call) Return(err error) *AuthServiceMock_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthServiceMock_Logout_Call) RunAndReturn(run func(context1 context.Context, credentials session.Credentials) error) *AuthServiceMock_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// NewHealthGatewayMock creates a new instance of HealthGatewayMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthGatewayMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthGatewayMock {
	mock := &HealthGatewayMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HealthGatewayMock is an autogenerated mock type for the HealthGateway type
type HealthGatewayMock struct {
	mock.Mock
}

type HealthGatewayMock_Expecter struct {
	mock *mock.Mock
}

func (_m *HealthGatewayMock) EXPECT() *HealthGatewayMock_Expecter {
	return &HealthGatewayMock_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type HealthGatewayMock
func (_mock *HealthGatewayMock) Check(context1 context.Context) health.Report {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 health.Report
	if returnFunc, ok := ret.Get(0).(func(context.Context) health.Report); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(health.Report)
	}
	return r0
}

// HealthGatewayMock_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type HealthGatewayMock_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - context1 context.Context
func (_e *HealthGatewayMock_Expecter) Check(context1 interface{}) *HealthGatewayMock_Check_Call {
	return &HealthGatewayMock_Check_Call{Call: _e.mock.On("Check", context1)}
}

func (_c *HealthGatewayMock_Check_Call) Run(run func(context1 context.Context)) *HealthGatewayMock_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HealthGatewayMock_Check_Call) Return(report health.Report) *HealthGatewayMock_Check_Call {
	_c.Call.Return(report)
	return _c
}

func (_c *HealthGatewayMock_Check_Call) RunAndReturn(run func(context1 context.Context) health.Report) *HealthGatewayMock_Check_Call {
	_c.Call.Return(run)
	return _c
}

// NewOAuthServiceMock creates a new instance of OAuthServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOAuthServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OAuthServiceMock {
	mock := &OAuthServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OAuthServiceMock is an autogenerated mock type for the OAuthService type
type OAuthServiceMock struct {
	mock.Mock
}

type OAuthServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OAuthServiceMock) EXPECT() *OAuthServiceMock_Expecter {
	return &OAuthServiceMock_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type OAuthServiceMock
func (_mock *OAuthServiceMock) Begin(context1 context.Context, start oauth.Start) (oauth.Redirect, error) {
	ret := _mock.Called(context1, start)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 oauth.Redirect
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth.Start) (oauth.Redirect, error)); ok {
		return returnFunc(context1, start)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth.Start) oauth.Redirect); ok {
		r0 = returnFunc(context1, start)
	} else {
		r0 = ret.Get(0).(oauth.Redirect)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oauth.Start) error); ok {
		r1 = returnFunc(context1, start)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OAuthServiceMock_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type OAuthServiceMock_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - context1 context.Context
//   - start oauth.Start
func (_e *OAuthServiceMock_Expecter) Begin(context1 interface{}, start interface{}) *OAuthServiceMock_Begin_Call {
	return &OAuthServiceMock_Begin_Call{Call: _e.mock.On("Begin", context1, start)}
}

func (_c *OAuthServiceMock_Begin_Call) Run(run func(context1 context.Context, start oauth.Start)) *OAuthServiceMock_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oauth.Start
		if args[1] != nil {
			arg1 = args[1].(oauth.Start)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OAuthServiceMock_Begin_Call) Return(redirect oauth.Redirect, err error) *OAuthServiceMock_Begin_Call {
	_c.Call.Return(redirect, err)
	return _c
}

func (_c *OAuthServiceMock_Begin_Call) RunAndReturn(run func(context1 context.Context, start oauth.Start) (oauth.Redirect, error)) *OAuthServiceMock_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Complete provides a mock function for the type OAuthServiceMock
func (_mock *OAuthServiceMock) Complete(context1 context.Context, callback oauth.Callback) (oauth.Login, error) {
	ret := _mock.Called(context1, callback)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 oauth.Login
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth.Callback) (oauth.Login, error)); ok {
		return returnFunc(context1, callback)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth.Callback) oauth.Login); ok {
		r0 = returnFunc(context1, callback)
	} else {
		r0 = ret.Get(0).(oauth.Login)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oauth.Callback) error); ok {
		r1 = returnFunc(context1, callback)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OAuthServiceMock_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type OAuthServiceMock_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - context1 context.Context
//   - callback oauth.Callback
func (_e *OAuthServiceMock_Expecter) Complete(context1 interface{}, callback interface{}) *OAuthServiceMock_Complete_Call {
	return &OAuthServiceMock_Complete_Call{Call: _e.mock.On("Complete", context1, callback)}
}

func (_c *OAuthServiceMock_Complete_Call) Run(run func(context1 context.Context, callback oauth.Callback)) *OAuthServiceMock_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oauth.Callback
		if args[1] != nil {
			arg1 = args[1].(oauth.Callback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OAuthServiceMock_Complete_Call) Return(login oauth.Login, err error) *OAuthServiceMock_Complete_Call {
	_c.Call.Return(login, err)
	return _c
}

func (_c *OAuthServiceMock_Complete_Call) RunAndReturn(run func(context1 context.Context, callback oauth.Callback) (oauth.Login, error)) *OAuthServiceMock_Complete_Call {
	_c.Call.Return(run)
	return _c
}
