// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"

	"github.com/pl3lee/uwplan/api/internal/domain/course"
	"github.com/pl3lee/uwplan/api/internal/domain/health"
	"github.com/pl3lee/uwplan/api/internal/domain/oauth"
	"github.com/pl3lee/uwplan/api/internal/domain/schedule"
	"github.com/pl3lee/uwplan/api/internal/domain/session"
	"github.com/pl3lee/uwplan/api/internal/domain/template"
	"github.com/pl3lee/uwplan/api/internal/domain/term"
	"github.com/pl3lee/uwplan/api/internal/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthServiceMock creates a new instance of AuthServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServiceMock {
	mock := &AuthServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthServiceMock is an autogenerated mock type for the AuthService type
type AuthServiceMock struct {
	mock.Mock
}

type AuthServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthServiceMock) EXPECT() *AuthServiceMock_Expecter {
	return &AuthServiceMock_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) Authenticate(context1 context.Context, credentials session.Credentials) (user.User, error) {
	ret := _mock.Called(context1, credentials)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.Credentials) (user.User, error)); ok {
		return returnFunc(context1, credentials)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.Credentials) user.User); ok {
		r0 = returnFunc(context1, credentials)
	} else {
		r0 = ret.Get(0).(user.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, session.Credentials) error); ok {
		r1 = returnFunc(context1, credentials)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthServiceMock_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type AuthServiceMock_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - context1 context.Context
//   - credentials session.Credentials
func (_e *AuthServiceMock_Expecter) Authenticate(context1 interface{}, credentials interface{}) *AuthServiceMock_Authenticate_Call {
	return &AuthServiceMock_Authenticate_Call{Call: _e.mock.On("Authenticate", context1, credentials)}
}

func (_c *AuthServiceMock_Authenticate_Call) Run(run func(context1 context.Context, credentials session.Credentials)) *AuthServiceMock_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 session.Credentials
		if args[1] != nil {
			arg1 = args[1].(session.Credentials)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthServiceMock_Authenticate_Call) Return(user1 user.User, err error) *AuthServiceMock_Authenticate_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *AuthServiceMock_Authenticate_Call) RunAndReturn(run func(context1 context.Context, credentials session.Credentials) (user.User, error)) *AuthServiceMock_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) Logout(context1 context.Context, credentials session.Credentials) error {
	ret := _mock.Called(context1, credentials)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.Credentials) error); ok {
		r0 = returnFunc(context1, credentials)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthServiceMock_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AuthServiceMock_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - context1 context.Context
//   - credentials session.Credentials
func (_e *AuthServiceMock_Expecter) Logout(context1 interface{}, credentials interface{}) *AuthServiceMock_Logout_Call {
	return &AuthServiceMock_Logout_Call{Call: _e.mock.On("Logout", context1, credentials)}
}

func (_c *AuthServiceMock_Logout_Call) Run(run func(context1 context.Context, credentials session.Credentials)) *AuthServiceMock_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 session.Credentials
		if args[1] != nil {
			arg1 = args[1].(session.Credentials)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthServiceMock_Logout_Call) Return(err error) *AuthServiceMock_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthServiceMock_Logout_Call) RunAndReturn(run func(context1 context.Context, credentials session.Credentials) error) *AuthServiceMock_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// NewCourseServiceMock creates a new instance of CourseServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseServiceMock {
	mock := &CourseServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CourseServiceMock is an autogenerated mock type for the CourseService type
type CourseServiceMock struct {
	mock.Mock
}

type CourseServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CourseServiceMock) EXPECT() *CourseServiceMock_Expecter {
	return &CourseServiceMock_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type CourseServiceMock
func (_mock *CourseServiceMock) List(context1 context.Context) ([]course.Course, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []course.Course
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]course.Course, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []course.Course); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]course.Course)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CourseServiceMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type CourseServiceMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
func (_e *CourseServiceMock_Expecter) List(context1 interface{}) *CourseServiceMock_List_Call {
	return &CourseServiceMock_List_Call{Call: _e.mock.On("List", context1)}
}

func (_c *CourseServiceMock_List_Call) Run(run func(context1 context.Context)) *CourseServiceMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CourseServiceMock_List_Call) Return(courses []course.Course, err error) *CourseServiceMock_List_Call {
	_c.Call.Return(courses, err)
	return _c
}

func (_c *CourseServiceMock_List_Call) RunAndReturn(run func(context1 context.Context) ([]course.Course, error)) *CourseServiceMock_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewTemplateServiceMock creates a new instance of TemplateServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTemplateServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TemplateServiceMock {
	mock := &TemplateServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TemplateServiceMock is an autogenerated mock type for the TemplateService type
type TemplateServiceMock struct {
	mock.Mock
}

type TemplateServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TemplateServiceMock) EXPECT() *TemplateServiceMock_Expecter {
	return &TemplateServiceMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type TemplateServiceMock
func (_mock *TemplateServiceMock) Create(context1 context.Context, draft template.Draft) (template.Template, error) {
	ret := _mock.Called(context1, draft)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 template.Template
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, template.Draft) (template.Template, error)); ok {
		return returnFunc(context1, draft)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, template.Draft) template.Template); ok {
		r0 = returnFunc(context1, draft)
	} else {
		r0 = ret.Get(0).(template.Template)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, template.Draft) error); ok {
		r1 = returnFunc(context1, draft)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TemplateServiceMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TemplateServiceMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - draft template.Draft
func (_e *TemplateServiceMock_Expecter) Create(context1 interface{}, draft interface{}) *TemplateServiceMock_Create_Call {
	return &TemplateServiceMock_Create_Call{Call: _e.mock.On("Create", context1, draft)}
}

func (_c *TemplateServiceMock_Create_Call) Run(run func(context1 context.Context, draft template.Draft)) *TemplateServiceMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 template.Draft
		if args[1] != nil {
			arg1 = args[1].(template.Draft)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TemplateServiceMock_Create_Call) Return(template1 template.Template, err error) *TemplateServiceMock_Create_Call {
	_c.Call.Return(template1, err)
	return _c
}

func (_c *TemplateServiceMock_Create_Call) RunAndReturn(run func(context1 context.Context, draft template.Draft) (template.Template, error)) *TemplateServiceMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type TemplateServiceMock
func (_mock *TemplateServiceMock) Delete(context1 context.Context, reference template.Reference) error {
	ret := _mock.Called(context1, reference)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, template.Reference) error); ok {
		r0 = returnFunc(context1, reference)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TemplateServiceMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TemplateServiceMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - reference template.Reference
func (_e *TemplateServiceMock_Expecter) Delete(context1 interface{}, reference interface{}) *TemplateServiceMock_Delete_Call {
	return &TemplateServiceMock_Delete_Call{Call: _e.mock.On("Delete", context1, reference)}
}

func (_c *TemplateServiceMock_Delete_Call) Run(run func(context1 context.Context, reference template.Reference)) *TemplateServiceMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 template.Reference
		if args[1] != nil {
			arg1 = args[1].(template.Reference)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TemplateServiceMock_Delete_Call) Return(err error) *TemplateServiceMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TemplateServiceMock_Delete_Call) RunAndReturn(run func(context1 context.Context, reference template.Reference) error) *TemplateServiceMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type TemplateServiceMock
func (_mock *TemplateServiceMock) Get(context1 context.Context, reference template.Reference) (template.Definition, error) {
	ret := _mock.Called(context1, reference)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 template.Definition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, template.Reference) (template.Definition, error)); ok {
		return returnFunc(context1, reference)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, template.Reference) template.Definition); ok {
		r0 = returnFunc(context1, reference)
	} else {
		r0 = ret.Get(0).(template.Definition)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, template.Reference) error); ok {
		r1 = returnFunc(context1, reference)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TemplateServiceMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TemplateServiceMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - reference template.Reference
func (_e *TemplateServiceMock_Expecter) Get(context1 interface{}, reference interface{}) *TemplateServiceMock_Get_Call {
	return &TemplateServiceMock_Get_Call{Call: _e.mock.On("Get", context1, reference)}
}

func (_c *TemplateServiceMock_Get_Call) Run(run func(context1 context.Context, reference template.Reference)) *TemplateServiceMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 template.Reference
		if args[1] != nil {
			arg1 = args[1].(template.Reference)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TemplateServiceMock_Get_Call) Return(definition template.Definition, err error) *TemplateServiceMock_Get_Call {
	_c.Call.Return(definition, err)
	return _c
}

func (_c *TemplateServiceMock_Get_Call) RunAndReturn(run func(context1 context.Context, reference template.Reference) (template.Definition, error)) *TemplateServiceMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type TemplateServiceMock
func (_mock *TemplateServiceMock) List(context1 context.Context, list template.List) ([]template.Template, error) {
	ret := _mock.Called(context1, list)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []template.Template
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, template.List) ([]template.Template, error)); ok {
		return returnFunc(context1, list)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, template.List) []template.Template); ok {
		r0 = returnFunc(context1, list)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]template.Template)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, template.List) error); ok {
		r1 = returnFunc(context1, list)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TemplateServiceMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TemplateServiceMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - list template.List
func (_e *TemplateServiceMock_Expecter) List(context1 interface{}, list interface{}) *TemplateServiceMock_List_Call {
	return &TemplateServiceMock_List_Call{Call: _e.mock.On("List", context1, list)}
}

func (_c *TemplateServiceMock_List_Call) Run(run func(context1 context.Context, list template.List)) *TemplateServiceMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 template.List
		if args[1] != nil {
			arg1 = args[1].(template.List)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TemplateServiceMock_List_Call) Return(templates []template.Template, err error) *TemplateServiceMock_List_Call {
	_c.Call.Return(templates, err)
	return _c
}

func (_c *TemplateServiceMock_List_Call) RunAndReturn(run func(context1 context.Context, list template.List) ([]template.Template, error)) *TemplateServiceMock_List_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type TemplateServiceMock
func (_mock *TemplateServiceMock) Rename(context1 context.Context, rename template.Rename) error {
	ret := _mock.Called(context1, rename)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, template.Rename) error); ok {
		r0 = returnFunc(context1, rename)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TemplateServiceMock_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type TemplateServiceMock_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - context1 context.Context
//   - rename template.Rename
func (_e *TemplateServiceMock_Expecter) Rename(context1 interface{}, rename interface{}) *TemplateServiceMock_Rename_Call {
	return &TemplateServiceMock_Rename_Call{Call: _e.mock.On("Rename", context1, rename)}
}

func (_c *TemplateServiceMock_Rename_Call) Run(run func(context1 context.Context, rename template.Rename)) *TemplateServiceMock_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 template.Rename
		if args[1] != nil {
			arg1 = args[1].(template.Rename)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TemplateServiceMock_Rename_Call) Return(err error) *TemplateServiceMock_Rename_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TemplateServiceMock_Rename_Call) RunAndReturn(run func(context1 context.Context, rename template.Rename) error) *TemplateServiceMock_Rename_Call {
	_c.Call.Return(run)
	return _c
}

// NewScheduleServiceMock creates a new instance of ScheduleServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScheduleServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScheduleServiceMock {
	mock := &ScheduleServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ScheduleServiceMock is an autogenerated mock type for the ScheduleService type
type ScheduleServiceMock struct {
	mock.Mock
}

type ScheduleServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ScheduleServiceMock) EXPECT() *ScheduleServiceMock_Expecter {
	return &ScheduleServiceMock_Expecter{mock: &_m.Mock}
}

// Assign provides a mock function for the type ScheduleServiceMock
func (_mock *ScheduleServiceMock) Assign(context1 context.Context, assign schedule.Assign) error {
	ret := _mock.Called(context1, assign)

	if len(ret) == 0 {
		panic("no return value specified for Assign")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, schedule.Assign) error); ok {
		r0 = returnFunc(context1, assign)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ScheduleServiceMock_Assign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assign'
type ScheduleServiceMock_Assign_Call struct {
	*mock.Call
}

// Assign is a helper method to define mock.On call
//   - context1 context.Context
//   - assign schedule.Assign
func (_e *ScheduleServiceMock_Expecter) Assign(context1 interface{}, assign interface{}) *ScheduleServiceMock_Assign_Call {
	return &ScheduleServiceMock_Assign_Call{Call: _e.mock.On("Assign", context1, assign)}
}

func (_c *ScheduleServiceMock_Assign_Call) Run(run func(context1 context.Context, assign schedule.Assign)) *ScheduleServiceMock_Assign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 schedule.Assign
		if args[1] != nil {
			arg1 = args[1].(schedule.Assign)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScheduleServiceMock_Assign_Call) Return(err error) *ScheduleServiceMock_Assign_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ScheduleServiceMock_Assign_Call) RunAndReturn(run func(context1 context.Context, assign schedule.Assign) error) *ScheduleServiceMock_Assign_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeTermRange provides a mock function for the type ScheduleServiceMock
func (_mock *ScheduleServiceMock) ChangeTermRange(context1 context.Context, termRangeChange schedule.TermRangeChange) error {
	ret := _mock.Called(context1, termRangeChange)

	if len(ret) == 0 {
		panic("no return value specified for ChangeTermRange")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, schedule.TermRangeChange) error); ok {
		r0 = returnFunc(context1, termRangeChange)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ScheduleServiceMock_ChangeTermRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeTermRange'
type ScheduleServiceMock_ChangeTermRange_Call struct {
	*mock.Call
}

// ChangeTermRange is a helper method to define mock.On call
//   - context1 context.Context
//   - termRangeChange schedule.TermRangeChange
func (_e *ScheduleServiceMock_Expecter) ChangeTermRange(context1 interface{}, termRangeChange interface{}) *ScheduleServiceMock_ChangeTermRange_Call {
	return &ScheduleServiceMock_ChangeTermRange_Call{Call: _e.mock.On("ChangeTermRange", context1, termRangeChange)}
}

func (_c *ScheduleServiceMock_ChangeTermRange_Call) Run(run func(context1 context.Context, termRangeChange schedule.TermRangeChange)) *ScheduleServiceMock_ChangeTermRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 schedule.TermRangeChange
		if args[1] != nil {
			arg1 = args[1].(schedule.TermRangeChange)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScheduleServiceMock_ChangeTermRange_Call) Return(err error) *ScheduleServiceMock_ChangeTermRange_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ScheduleServiceMock_ChangeTermRange_Call) RunAndReturn(run func(context1 context.Context, termRangeChange schedule.TermRangeChange) error) *ScheduleServiceMock_ChangeTermRange_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type ScheduleServiceMock
func (_mock *ScheduleServiceMock) Create(context1 context.Context, create schedule.Create) (schedule.Schedule, error) {
	ret := _mock.Called(context1, create)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 schedule.Schedule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, schedule.Create) (schedule.Schedule, error)); ok {
		return returnFunc(context1, create)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, schedule.Create) schedule.Schedule); ok {
		r0 = returnFunc(context1, create)
	} else {
		r0 = ret.Get(0).(schedule.Schedule)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, schedule.Create) error); ok {
		r1 = returnFunc(context1, create)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ScheduleServiceMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ScheduleServiceMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - create schedule.Create
func (_e *ScheduleServiceMock_Expecter) Create(context1 interface{}, create interface{}) *ScheduleServiceMock_Create_Call {
	return &ScheduleServiceMock_Create_Call{Call: _e.mock.On("Create", context1, create)}
}

func (_c *ScheduleServiceMock_Create_Call) Run(run func(context1 context.Context, create schedule.Create)) *ScheduleServiceMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 schedule.Create
		if args[1] != nil {
			arg1 = args[1].(schedule.Create)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScheduleServiceMock_Create_Call) Return(schedule1 schedule.Schedule, err error) *ScheduleServiceMock_Create_Call {
	_c.Call.Return(schedule1, err)
	return _c
}

func (_c *ScheduleServiceMock_Create_Call) RunAndReturn(run func(context1 context.Context, create schedule.Create) (schedule.Schedule, error)) *ScheduleServiceMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ScheduleServiceMock
func (_mock *ScheduleServiceMock) Delete(context1 context.Context, reference schedule.Reference) error {
	ret := _mock.Called(context1, reference)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, schedule.Reference) error); ok {
		r0 = returnFunc(context1, reference)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ScheduleServiceMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ScheduleServiceMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - reference schedule.Reference
func (_e *ScheduleServiceMock_Expecter) Delete(context1 interface{}, reference interface{}) *ScheduleServiceMock_Delete_Call {
	return &ScheduleServiceMock_Delete_Call{Call: _e.mock.On("Delete", context1, reference)}
}

func (_c *ScheduleServiceMock_Delete_Call) Run(run func(context1 context.Context, reference schedule.Reference)) *ScheduleServiceMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 schedule.Reference
		if args[1] != nil {
			arg1 = args[1].(schedule.Reference)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScheduleServiceMock_Delete_Call) Return(err error) *ScheduleServiceMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ScheduleServiceMock_Delete_Call) RunAndReturn(run func(context1 context.Context, reference schedule.Reference) error) *ScheduleServiceMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetTermRange provides a mock function for the type ScheduleServiceMock
func (_mock *ScheduleServiceMock) GetTermRange(context1 context.Context, user1 user.User) (term.Range, error) {
	ret := _mock.Called(context1, user1)

	if len(ret) == 0 {
		panic("no return value specified for GetTermRange")
	}

	var r0 term.Range
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) (term.Range, error)); ok {
		return returnFunc(context1, user1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) term.Range); ok {
		r0 = returnFunc(context1, user1)
	} else {
		r0 = ret.Get(0).(term.Range)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.User) error); ok {
		r1 = returnFunc(context1, user1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ScheduleServiceMock_GetTermRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTermRange'
type ScheduleServiceMock_GetTermRange_Call struct {
	*mock.Call
}

// GetTermRange is a helper method to define mock.On call
//   - context1 context.Context
//   - user1 user.User
func (_e *ScheduleServiceMock_Expecter) GetTermRange(context1 interface{}, user1 interface{}) *ScheduleServiceMock_GetTermRange_Call {
	return &ScheduleServiceMock_GetTermRange_Call{Call: _e.mock.On("GetTermRange", context1, user1)}
}

func (_c *ScheduleServiceMock_GetTermRange_Call) Run(run func(context1 context.Context, user1 user.User)) *ScheduleServiceMock_GetTermRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.User
		if args[1] != nil {
			arg1 = args[1].(user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScheduleServiceMock_GetTermRange_Call) Return(rangeParam term.Range, err error) *ScheduleServiceMock_GetTermRange_Call {
	_c.Call.Return(rangeParam, err)
	return _c
}

func (_c *ScheduleServiceMock_GetTermRange_Call) RunAndReturn(run func(context1 context.Context, user1 user.User) (term.Range, error)) *ScheduleServiceMock_GetTermRange_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type ScheduleServiceMock
func (_mock *ScheduleServiceMock) List(context1 context.Context, user1 user.User) (schedule.Collection, error) {
	ret := _mock.Called(context1, user1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 schedule.Collection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) (schedule.Collection, error)); ok {
		return returnFunc(context1, user1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) schedule.Collection); ok {
		r0 = returnFunc(context1, user1)
	} else {
		r0 = ret.Get(0).(schedule.Collection)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.User) error); ok {
		r1 = returnFunc(context1, user1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ScheduleServiceMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ScheduleServiceMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - user1 user.User
func (_e *ScheduleServiceMock_Expecter) List(context1 interface{}, user1 interface{}) *ScheduleServiceMock_List_Call {
	return &ScheduleServiceMock_List_Call{Call: _e.mock.On("List", context1, user1)}
}

func (_c *ScheduleServiceMock_List_Call) Run(run func(context1 context.Context, user1 user.User)) *ScheduleServiceMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.User
		if args[1] != nil {
			arg1 = args[1].(user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScheduleServiceMock_List_Call) Return(collection schedule.Collection, err error) *ScheduleServiceMock_List_Call {
	_c.Call.Return(collection, err)
	return _c
}

func (_c *ScheduleServiceMock_List_Call) RunAndReturn(run func(context1 context.Context, user1 user.User) (schedule.Collection, error)) *ScheduleServiceMock_List_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveCourse provides a mock function for the type ScheduleServiceMock
func (_mock *ScheduleServiceMock) RemoveCourse(context1 context.Context, removeCourse schedule.RemoveCourse) error {
	ret := _mock.Called(context1, removeCourse)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCourse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, schedule.RemoveCourse) error); ok {
		r0 = returnFunc(context1, removeCourse)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ScheduleServiceMock_RemoveCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveCourse'
type ScheduleServiceMock_RemoveCourse_Call struct {
	*mock.Call
}

// RemoveCourse is a helper method to define mock.On call
//   - context1 context.Context
//   - removeCourse schedule.RemoveCourse
func (_e *ScheduleServiceMock_Expecter) RemoveCourse(context1 interface{}, removeCourse interface{}) *ScheduleServiceMock_RemoveCourse_Call {
	return &ScheduleServiceMock_RemoveCourse_Call{Call: _e.mock.On("RemoveCourse", context1, removeCourse)}
}

func (_c *ScheduleServiceMock_RemoveCourse_Call) Run(run func(context1 context.Context, removeCourse schedule.RemoveCourse)) *ScheduleServiceMock_RemoveCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 schedule.RemoveCourse
		if args[1] != nil {
			arg1 = args[1].(schedule.RemoveCourse)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScheduleServiceMock_RemoveCourse_Call) Return(err error) *ScheduleServiceMock_RemoveCourse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ScheduleServiceMock_RemoveCourse_Call) RunAndReturn(run func(context1 context.Context, removeCourse schedule.RemoveCourse) error) *ScheduleServiceMock_RemoveCourse_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type ScheduleServiceMock
func (_mock *ScheduleServiceMock) Rename(context1 context.Context, rename schedule.Rename) error {
	ret := _mock.Called(context1, rename)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, schedule.Rename) error); ok {
		r0 = returnFunc(context1, rename)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ScheduleServiceMock_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type ScheduleServiceMock_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - context1 context.Context
//   - rename schedule.Rename
func (_e *ScheduleServiceMock_Expecter) Rename(context1 interface{}, rename interface{}) *ScheduleServiceMock_Rename_Call {
	return &ScheduleServiceMock_Rename_Call{Call: _e.mock.On("Rename", context1, rename)}
}

func (_c *ScheduleServiceMock_Rename_Call) Run(run func(context1 context.Context, rename schedule.Rename)) *ScheduleServiceMock_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 schedule.Rename
		if args[1] != nil {
			arg1 = args[1].(schedule.Rename)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScheduleServiceMock_Rename_Call) Return(err error) *ScheduleServiceMock_Rename_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ScheduleServiceMock_Rename_Call) RunAndReturn(run func(context1 context.Context, rename schedule.Rename) error) *ScheduleServiceMock_Rename_Call {
	_c.Call.Return(run)
	return _c
}

// View provides a mock function for the type ScheduleServiceMock
func (_mock *ScheduleServiceMock) View(context1 context.Context, reference schedule.Reference) (schedule.View, error) {
	ret := _mock.Called(context1, reference)

	if len(ret) == 0 {
		panic("no return value specified for View")
	}

	var r0 schedule.View
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, schedule.Reference) (schedule.View, error)); ok {
		return returnFunc(context1, reference)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, schedule.Reference) schedule.View); ok {
		r0 = returnFunc(context1, reference)
	} else {
		r0 = ret.Get(0).(schedule.View)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, schedule.Reference) error); ok {
		r1 = returnFunc(context1, reference)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ScheduleServiceMock_View_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'View'
type ScheduleServiceMock_View_Call struct {
	*mock.Call
}

// View is a helper method to define mock.On call
//   - context1 context.Context
//   - reference schedule.Reference
func (_e *ScheduleServiceMock_Expecter) View(context1 interface{}, reference interface{}) *ScheduleServiceMock_View_Call {
	return &ScheduleServiceMock_View_Call{Call: _e.mock.On("View", context1, reference)}
}

func (_c *ScheduleServiceMock_View_Call) Run(run func(context1 context.Context, reference schedule.Reference)) *ScheduleServiceMock_View_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 schedule.Reference
		if args[1] != nil {
			arg1 = args[1].(schedule.Reference)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScheduleServiceMock_View_Call) Return(view schedule.View, err error) *ScheduleServiceMock_View_Call {
	_c.Call.Return(view, err)
	return _c
}

func (_c *ScheduleServiceMock_View_Call) RunAndReturn(run func(context1 context.Context, reference schedule.Reference) (schedule.View, error)) *ScheduleServiceMock_View_Call {
	_c.Call.Return(run)
	return _c
}

// NewHealthGatewayMock creates a new instance of HealthGatewayMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthGatewayMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthGatewayMock {
	mock := &HealthGatewayMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HealthGatewayMock is an autogenerated mock type for the HealthGateway type
type HealthGatewayMock struct {
	mock.Mock
}

type HealthGatewayMock_Expecter struct {
	mock *mock.Mock
}

func (_m *HealthGatewayMock) EXPECT() *HealthGatewayMock_Expecter {
	return &HealthGatewayMock_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type HealthGatewayMock
func (_mock *HealthGatewayMock) Check(context1 context.Context) health.Report {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 health.Report
	if returnFunc, ok := ret.Get(0).(func(context.Context) health.Report); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(health.Report)
	}
	return r0
}

// HealthGatewayMock_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type HealthGatewayMock_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - context1 context.Context
func (_e *HealthGatewayMock_Expecter) Check(context1 interface{}) *HealthGatewayMock_Check_Call {
	return &HealthGatewayMock_Check_Call{Call: _e.mock.On("Check", context1)}
}

func (_c *HealthGatewayMock_Check_Call) Run(run func(context1 context.Context)) *HealthGatewayMock_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HealthGatewayMock_Check_Call) Return(report health.Report) *HealthGatewayMock_Check_Call {
	_c.Call.Return(report)
	return _c
}

func (_c *HealthGatewayMock_Check_Call) RunAndReturn(run func(context1 context.Context) health.Report) *HealthGatewayMock_Check_Call {
	_c.Call.Return(run)
	return _c
}

// NewOAuthServiceMock creates a new instance of OAuthServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOAuthServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OAuthServiceMock {
	mock := &OAuthServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OAuthServiceMock is an autogenerated mock type for the OAuthService type
type OAuthServiceMock struct {
	mock.Mock
}

type OAuthServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OAuthServiceMock) EXPECT() *OAuthServiceMock_Expecter {
	return &OAuthServiceMock_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type OAuthServiceMock
func (_mock *OAuthServiceMock) Begin(context1 context.Context, start oauth.Start) (oauth.Redirect, error) {
	ret := _mock.Called(context1, start)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 oauth.Redirect
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth.Start) (oauth.Redirect, error)); ok {
		return returnFunc(context1, start)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth.Start) oauth.Redirect); ok {
		r0 = returnFunc(context1, start)
	} else {
		r0 = ret.Get(0).(oauth.Redirect)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oauth.Start) error); ok {
		r1 = returnFunc(context1, start)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OAuthServiceMock_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type OAuthServiceMock_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - context1 context.Context
//   - start oauth.Start
func (_e *OAuthServiceMock_Expecter) Begin(context1 interface{}, start interface{}) *OAuthServiceMock_Begin_Call {
	return &OAuthServiceMock_Begin_Call{Call: _e.mock.On("Begin", context1, start)}
}

func (_c *OAuthServiceMock_Begin_Call) Run(run func(context1 context.Context, start oauth.Start)) *OAuthServiceMock_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oauth.Start
		if args[1] != nil {
			arg1 = args[1].(oauth.Start)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OAuthServiceMock_Begin_Call) Return(redirect oauth.Redirect, err error) *OAuthServiceMock_Begin_Call {
	_c.Call.Return(redirect, err)
	return _c
}

func (_c *OAuthServiceMock_Begin_Call) RunAndReturn(run func(context1 context.Context, start oauth.Start) (oauth.Redirect, error)) *OAuthServiceMock_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Complete provides a mock function for the type OAuthServiceMock
func (_mock *OAuthServiceMock) Complete(context1 context.Context, callback oauth.Callback) (oauth.Login, error) {
	ret := _mock.Called(context1, callback)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 oauth.Login
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth.Callback) (oauth.Login, error)); ok {
		return returnFunc(context1, callback)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth.Callback) oauth.Login); ok {
		r0 = returnFunc(context1, callback)
	} else {
		r0 = ret.Get(0).(oauth.Login)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oauth.Callback) error); ok {
		r1 = returnFunc(context1, callback)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OAuthServiceMock_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type OAuthServiceMock_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - context1 context.Context
//   - callback oauth.Callback
func (_e *OAuthServiceMock_Expecter) Complete(context1 interface{}, callback interface{}) *OAuthServiceMock_Complete_Call {
	return &OAuthServiceMock_Complete_Call{Call: _e.mock.On("Complete", context1, callback)}
}

func (_c *OAuthServiceMock_Complete_Call) Run(run func(context1 context.Context, callback oauth.Callback)) *OAuthServiceMock_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oauth.Callback
		if args[1] != nil {
			arg1 = args[1].(oauth.Callback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OAuthServiceMock_Complete_Call) Return(login oauth.Login, err error) *OAuthServiceMock_Complete_Call {
	_c.Call.Return(login, err)
	return _c
}

func (_c *OAuthServiceMock_Complete_Call) RunAndReturn(run func(context1 context.Context, callback oauth.Callback) (oauth.Login, error)) *OAuthServiceMock_Complete_Call {
	_c.Call.Return(run)
	return _c
}
