// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oauth

import (
	"context"

	"github.com/pl3lee/uwplan/api/internal/domain/oauth"
	"github.com/pl3lee/uwplan/api/internal/domain/session"
	"github.com/pl3lee/uwplan/api/internal/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// NewOAuthRepositoryMock creates a new instance of OAuthRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOAuthRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OAuthRepositoryMock {
	mock := &OAuthRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OAuthRepositoryMock is an autogenerated mock type for the OAuthRepository type
type OAuthRepositoryMock struct {
	mock.Mock
}

type OAuthRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OAuthRepositoryMock) EXPECT() *OAuthRepositoryMock_Expecter {
	return &OAuthRepositoryMock_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function for the type OAuthRepositoryMock
func (_mock *OAuthRepositoryMock) Consume(context1 context.Context, flow oauth.Flow) (oauth.Flow, error) {
	ret := _mock.Called(context1, flow)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 oauth.Flow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth.Flow) (oauth.Flow, error)); ok {
		return returnFunc(context1, flow)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth.Flow) oauth.Flow); ok {
		r0 = returnFunc(context1, flow)
	} else {
		r0 = ret.Get(0).(oauth.Flow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oauth.Flow) error); ok {
		r1 = returnFunc(context1, flow)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OAuthRepositoryMock_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type OAuthRepositoryMock_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - context1 context.Context
//   - flow oauth.Flow
func (_e *OAuthRepositoryMock_Expecter) Consume(context1 interface{}, flow interface{}) *OAuthRepositoryMock_Consume_Call {
	return &OAuthRepositoryMock_Consume_Call{Call: _e.mock.On("Consume", context1, flow)}
}

func (_c *OAuthRepositoryMock_Consume_Call) Run(run func(context1 context.Context, flow oauth.Flow)) *OAuthRepositoryMock_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oauth.Flow
		if args[1] != nil {
			arg1 = args[1].(oauth.Flow)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OAuthRepositoryMock_Consume_Call) Return(flow1 oauth.Flow, err error) *OAuthRepositoryMock_Consume_Call {
	_c.Call.Return(flow1, err)
	return _c
}

func (_c *OAuthRepositoryMock_Consume_Call) RunAndReturn(run func(context1 context.Context, flow oauth.Flow) (oauth.Flow, error)) *OAuthRepositoryMock_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type OAuthRepositoryMock
func (_mock *OAuthRepositoryMock) Create(context1 context.Context, flow oauth.Flow) error {
	ret := _mock.Called(context1, flow)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth.Flow) error); ok {
		r0 = returnFunc(context1, flow)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OAuthRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OAuthRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - flow oauth.Flow
func (_e *OAuthRepositoryMock_Expecter) Create(context1 interface{}, flow interface{}) *OAuthRepositoryMock_Create_Call {
	return &OAuthRepositoryMock_Create_Call{Call: _e.mock.On("Create", context1, flow)}
}

func (_c *OAuthRepositoryMock_Create_Call) Run(run func(context1 context.Context, flow oauth.Flow)) *OAuthRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oauth.Flow
		if args[1] != nil {
			arg1 = args[1].(oauth.Flow)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OAuthRepositoryMock_Create_Call) Return(err error) *OAuthRepositoryMock_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OAuthRepositoryMock_Create_Call) RunAndReturn(run func(context1 context.Context, flow oauth.Flow) error) *OAuthRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewOAuthGatewayMock creates a new instance of OAuthGatewayMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOAuthGatewayMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OAuthGatewayMock {
	mock := &OAuthGatewayMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OAuthGatewayMock is an autogenerated mock type for the OAuthGateway type
type OAuthGatewayMock struct {
	mock.Mock
}

type OAuthGatewayMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OAuthGatewayMock) EXPECT() *OAuthGatewayMock_Expecter {
	return &OAuthGatewayMock_Expecter{mock: &_m.Mock}
}

// AuthorizationURL provides a mock function for the type OAuthGatewayMock
func (_mock *OAuthGatewayMock) AuthorizationURL(context1 context.Context, authorization oauth.Authorization) (oauth.Redirect, error) {
	ret := _mock.Called(context1, authorization)

	if len(ret) == 0 {
		panic("no return value specified for AuthorizationURL")
	}

	var r0 oauth.Redirect
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth.Authorization) (oauth.Redirect, error)); ok {
		return returnFunc(context1, authorization)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth.Authorization) oauth.Redirect); ok {
		r0 = returnFunc(context1, authorization)
	} else {
		r0 = ret.Get(0).(oauth.Redirect)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oauth.Authorization) error); ok {
		r1 = returnFunc(context1, authorization)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OAuthGatewayMock_AuthorizationURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizationURL'
type OAuthGatewayMock_AuthorizationURL_Call struct {
	*mock.Call
}

// AuthorizationURL is a helper method to define mock.On call
//   - context1 context.Context
//   - authorization oauth.Authorization
func (_e *OAuthGatewayMock_Expecter) AuthorizationURL(context1 interface{}, authorization interface{}) *OAuthGatewayMock_AuthorizationURL_Call {
	return &OAuthGatewayMock_AuthorizationURL_Call{Call: _e.mock.On("AuthorizationURL", context1, authorization)}
}

func (_c *OAuthGatewayMock_AuthorizationURL_Call) Run(run func(context1 context.Context, authorization oauth.Authorization)) *OAuthGatewayMock_AuthorizationURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oauth.Authorization
		if args[1] != nil {
			arg1 = args[1].(oauth.Authorization)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OAuthGatewayMock_AuthorizationURL_Call) Return(redirect oauth.Redirect, err error) *OAuthGatewayMock_AuthorizationURL_Call {
	_c.Call.Return(redirect, err)
	return _c
}

func (_c *OAuthGatewayMock_AuthorizationURL_Call) RunAndReturn(run func(context1 context.Context, authorization oauth.Authorization) (oauth.Redirect, error)) *OAuthGatewayMock_AuthorizationURL_Call {
	_c.Call.Return(run)
	return _c
}

// Exchange provides a mock function for the type OAuthGatewayMock
func (_mock *OAuthGatewayMock) Exchange(context1 context.Context, exchange oauth.Exchange) (user.Identity, error) {
	ret := _mock.Called(context1, exchange)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 user.Identity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth.Exchange) (user.Identity, error)); ok {
		return returnFunc(context1, exchange)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oauth.Exchange) user.Identity); ok {
		r0 = returnFunc(context1, exchange)
	} else {
		r0 = ret.Get(0).(user.Identity)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oauth.Exchange) error); ok {
		r1 = returnFunc(context1, exchange)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OAuthGatewayMock_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type OAuthGatewayMock_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - context1 context.Context
//   - exchange oauth.Exchange
func (_e *OAuthGatewayMock_Expecter) Exchange(context1 interface{}, exchange interface{}) *OAuthGatewayMock_Exchange_Call {
	return &OAuthGatewayMock_Exchange_Call{Call: _e.mock.On("Exchange", context1, exchange)}
}

func (_c *OAuthGatewayMock_Exchange_Call) Run(run func(context1 context.Context, exchange oauth.Exchange)) *OAuthGatewayMock_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oauth.Exchange
		if args[1] != nil {
			arg1 = args[1].(oauth.Exchange)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OAuthGatewayMock_Exchange_Call) Return(identity user.Identity, err error) *OAuthGatewayMock_Exchange_Call {
	_c.Call.Return(identity, err)
	return _c
}

func (_c *OAuthGatewayMock_Exchange_Call) RunAndReturn(run func(context1 context.Context, exchange oauth.Exchange) (user.Identity, error)) *OAuthGatewayMock_Exchange_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthServiceMock creates a new instance of AuthServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServiceMock {
	mock := &AuthServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthServiceMock is an autogenerated mock type for the AuthService type
type AuthServiceMock struct {
	mock.Mock
}

type AuthServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthServiceMock) EXPECT() *AuthServiceMock_Expecter {
	return &AuthServiceMock_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) Login(context1 context.Context, identity user.Identity) (session.Grant, error) {
	ret := _mock.Called(context1, identity)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 session.Grant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.Identity) (session.Grant, error)); ok {
		return returnFunc(context1, identity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.Identity) session.Grant); ok {
		r0 = returnFunc(context1, identity)
	} else {
		r0 = ret.Get(0).(session.Grant)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.Identity) error); ok {
		r1 = returnFunc(context1, identity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthServiceMock_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthServiceMock_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - context1 context.Context
//   - identity user.Identity
func (_e *AuthServiceMock_Expecter) Login(context1 interface{}, identity interface{}) *AuthServiceMock_Login_Call {
	return &AuthServiceMock_Login_Call{Call: _e.mock.On("Login", context1, identity)}
}

func (_c *AuthServiceMock_Login_Call) Run(run func(context1 context.Context, identity user.Identity)) *AuthServiceMock_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.Identity
		if args[1] != nil {
			arg1 = args[1].(user.Identity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthServiceMock_Login_Call) Return(grant session.Grant, err error) *AuthServiceMock_Login_Call {
	_c.Call.Return(grant, err)
	return _c
}

func (_c *AuthServiceMock_Login_Call) RunAndReturn(run func(context1 context.Context, identity user.Identity) (session.Grant, error)) *AuthServiceMock_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) Logout(context1 context.Context, credentials session.Credentials) error {
	ret := _mock.Called(context1, credentials)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.Credentials) error); ok {
		r0 = returnFunc(context1, credentials)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthServiceMock_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AuthServiceMock_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - context1 context.Context
//   - credentials session.Credentials
func (_e *AuthServiceMock_Expecter) Logout(context1 interface{}, credentials interface{}) *AuthServiceMock_Logout_Call {
	return &AuthServiceMock_Logout_Call{Call: _e.mock.On("Logout", context1, credentials)}
}

func (_c *AuthServiceMock_Logout_Call) Run(run func(context1 context.Context, credentials session.Credentials)) *AuthServiceMock_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 session.Credentials
		if args[1] != nil {
			arg1 = args[1].(session.Credentials)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthServiceMock_Logout_Call) Return(err error) *AuthServiceMock_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthServiceMock_Logout_Call) RunAndReturn(run func(context1 context.Context, credentials session.Credentials) error) *AuthServiceMock_Logout_Call {
	_c.Call.Return(run)
	return _c
}
