// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: course.sql

package sqlc

import (
	"context"
)

const listCatalogCourses = `-- name: ListCatalogCourses :many
SELECT id, code, name, useful_rating, liked_rating, easy_rating, num_ratings, description, prereqs, antireqs, coreqs FROM course ORDER BY code
`

func (q *Queries) ListCatalogCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCatalogCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.UsefulRating,
			&i.LikedRating,
			&i.EasyRating,
			&i.NumRatings,
			&i.Description,
			&i.Prereqs,
			&i.Antireqs,
			&i.Coreqs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
