// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CourseItemType string

const (
	CourseItemTypeFixed CourseItemType = "fixed"
	CourseItemTypeFree  CourseItemType = "free"
)

func (e *CourseItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourseItemType(s)
	case string:
		*e = CourseItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for CourseItemType: %T", src)
	}
	return nil
}

type NullCourseItemType struct {
	CourseItemType CourseItemType
	Valid          bool // Valid is true if CourseItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourseItemType) Scan(value interface{}) error {
	if value == nil {
		ns.CourseItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourseItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourseItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourseItemType), nil
}

type ItemType string

const (
	ItemTypeRequirement ItemType = "requirement"
	ItemTypeInstruction ItemType = "instruction"
	ItemTypeSeparator   ItemType = "separator"
)

func (e *ItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemType(s)
	case string:
		*e = ItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemType: %T", src)
	}
	return nil
}

type NullItemType struct {
	ItemType ItemType
	Valid    bool // Valid is true if ItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemType) Scan(value interface{}) error {
	if value == nil {
		ns.ItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemType), nil
}

type RoleType string

const (
	RoleTypeUser      RoleType = "user"
	RoleTypeModerator RoleType = "moderator"
	RoleTypeAdmin     RoleType = "admin"
)

func (e *RoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleType(s)
	case string:
		*e = RoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleType: %T", src)
	}
	return nil
}

type NullRoleType struct {
	RoleType RoleType
	Valid    bool // Valid is true if RoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.RoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleType), nil
}

type Season string

const (
	SeasonFall   Season = "Fall"
	SeasonWinter Season = "Winter"
	SeasonSpring Season = "Spring"
)

func (e *Season) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Season(s)
	case string:
		*e = Season(s)
	default:
		return fmt.Errorf("unsupported scan type for Season: %T", src)
	}
	return nil
}

type NullSeason struct {
	Season Season
	Valid  bool // Valid is true if Season is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSeason) Scan(value interface{}) error {
	if value == nil {
		ns.Season, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Season.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSeason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Season), nil
}

type Account struct {
	UserID            string
	Type              string
	Provider          string
	ProviderAccountID string
	RefreshToken      *string
	AccessToken       *string
	ExpiresAt         *int32
	TokenType         *string
	Scope             *string
	IDToken           *string
	SessionState      *string
}

type Course struct {
	ID           uuid.UUID
	Code         string
	Name         string
	UsefulRating pgtype.Numeric
	LikedRating  pgtype.Numeric
	EasyRating   pgtype.Numeric
	NumRatings   *int32
	Description  string
	Prereqs      string
	Antireqs     string
	Coreqs       string
}

type CourseItem struct {
	ID            uuid.UUID
	RequirementID uuid.UUID
	Type          CourseItemType
	CourseID      pgtype.UUID
}

type FreeCourse struct {
	ID             uuid.UUID
	CourseItemID   uuid.UUID
	UserID         string
	FilledCourseID uuid.UUID
}

type Plan struct {
	ID     uuid.UUID
	UserID string
}

type PlanTemplate struct {
	PlanID     uuid.UUID
	TemplateID uuid.UUID
}

type Schedule struct {
	ID     uuid.UUID
	Name   string
	PlanID uuid.UUID
}

type ScheduleCourse struct {
	ScheduleID uuid.UUID
	CourseID   uuid.UUID
	Term       string
}

type SelectedCourse struct {
	PlanID       uuid.UUID
	CourseItemID uuid.UUID
	Selected     bool
}

type Session struct {
	SessionToken string
	UserID       string
	Expires      pgtype.Timestamptz
}

type Template struct {
	ID          uuid.UUID
	Name        string
	Description *string
	CreatedBy   *string
}

type TemplateItem struct {
	ID          uuid.UUID
	TemplateID  uuid.UUID
	Type        ItemType
	Description *string
	OrderIndex  int32
}

type User struct {
	ID            string
	Name          *string
	Email         string
	EmailVerified pgtype.Timestamptz
	Image         *string
	Role          RoleType
}

type UserTermRange struct {
	UserID    string
	StartTerm Season
	StartYear int32
	EndTerm   Season
	EndYear   int32
}

type VerificationToken struct {
	Identifier string
	Token      string
	Expires    pgtype.Timestamptz
}
