// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: planning.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const lockPlanningMutation = `-- name: LockPlanningMutation :exec
SELECT pg_advisory_xact_lock_shared(hashtextextended('uwplan:planning:templates',0))
`

// All selection and assignment writers take the shared gate before a plan row.
// Template deletion takes it exclusively before discovering/locking plans, so
// membership cannot change underneath discovery and lock order cannot invert.
func (q *Queries) LockPlanningMutation(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockPlanningMutation)
	return err
}

const lockTemplateDeletion = `-- name: LockTemplateDeletion :exec
SELECT pg_advisory_xact_lock(hashtextextended('uwplan:planning:templates',0))
`

func (q *Queries) LockTemplateDeletion(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockTemplateDeletion)
	return err
}

const lockTemplatePlans = `-- name: LockTemplatePlans :many
SELECT p.id FROM plan p JOIN plan_template pt ON pt.plan_id=p.id
WHERE pt.template_id=$1 ORDER BY p.id FOR UPDATE OF p
`

func (q *Queries) LockTemplatePlans(ctx context.Context, templateID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockTemplatePlans, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcilePlanAssignments = `-- name: ReconcilePlanAssignments :exec
DELETE FROM schedule_course assignment USING schedule s
WHERE assignment.schedule_id=s.id AND s.plan_id=$1 AND NOT EXISTS (
    SELECT 1 FROM active_course_sources source
    WHERE source.plan_id=s.plan_id AND source.course_id=assignment.course_id
)
`

func (q *Queries) ReconcilePlanAssignments(ctx context.Context, planID uuid.UUID) error {
	_, err := q.db.Exec(ctx, reconcilePlanAssignments, planID)
	return err
}
