// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createOwnedSchedule = `-- name: CreateOwnedSchedule :one
INSERT INTO schedule(id,name,plan_id) SELECT $1,$2,p.id FROM plan p WHERE p.user_id=$3 RETURNING id,name
`

type CreateOwnedScheduleParams struct {
	ID     uuid.UUID
	Name   string
	UserID string
}

type CreateOwnedScheduleRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateOwnedSchedule(ctx context.Context, arg CreateOwnedScheduleParams) (CreateOwnedScheduleRow, error) {
	row := q.db.QueryRow(ctx, createOwnedSchedule, arg.ID, arg.Name, arg.UserID)
	var i CreateOwnedScheduleRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteOwnedSchedule = `-- name: DeleteOwnedSchedule :execrows
DELETE FROM schedule s USING plan p WHERE s.plan_id=p.id AND p.user_id=$1 AND s.id=$2
`

type DeleteOwnedScheduleParams struct {
	UserID string
	ID     uuid.UUID
}

func (q *Queries) DeleteOwnedSchedule(ctx context.Context, arg DeleteOwnedScheduleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOwnedSchedule, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listOwnedSchedules = `-- name: ListOwnedSchedules :many
SELECT s.id,s.name FROM schedule s JOIN plan p ON p.id=s.plan_id WHERE p.user_id=$1 ORDER BY s.id
`

type ListOwnedSchedulesRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) ListOwnedSchedules(ctx context.Context, userID string) ([]ListOwnedSchedulesRow, error) {
	rows, err := q.db.Query(ctx, listOwnedSchedules, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnedSchedulesRow{}
	for rows.Next() {
		var i ListOwnedSchedulesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOwnedPlan = `-- name: LockOwnedPlan :one
SELECT id FROM plan WHERE user_id=$1 FOR UPDATE
`

func (q *Queries) LockOwnedPlan(ctx context.Context, userID string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockOwnedPlan, userID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const renameOwnedSchedule = `-- name: RenameOwnedSchedule :execrows
UPDATE schedule s SET name=$3 FROM plan p WHERE s.plan_id=p.id AND p.user_id=$1 AND s.id=$2
`

type RenameOwnedScheduleParams struct {
	UserID string
	ID     uuid.UUID
	Name   string
}

func (q *Queries) RenameOwnedSchedule(ctx context.Context, arg RenameOwnedScheduleParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameOwnedSchedule, arg.UserID, arg.ID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
