// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: selection.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachPlanTemplate = `-- name: AttachPlanTemplate :exec
INSERT INTO plan_template(plan_id,template_id) VALUES ($1,$2) ON CONFLICT DO NOTHING
`

type AttachPlanTemplateParams struct {
	PlanID     uuid.UUID
	TemplateID uuid.UUID
}

func (q *Queries) AttachPlanTemplate(ctx context.Context, arg AttachPlanTemplateParams) error {
	_, err := q.db.Exec(ctx, attachPlanTemplate, arg.PlanID, arg.TemplateID)
	return err
}

const clearFreeCourse = `-- name: ClearFreeCourse :exec
DELETE FROM free_course WHERE user_id=$1 AND course_item_id=$2
`

type ClearFreeCourseParams struct {
	UserID       string
	CourseItemID uuid.UUID
}

func (q *Queries) ClearFreeCourse(ctx context.Context, arg ClearFreeCourseParams) error {
	_, err := q.db.Exec(ctx, clearFreeCourse, arg.UserID, arg.CourseItemID)
	return err
}

const deselectTemplateChoices = `-- name: DeselectTemplateChoices :exec
UPDATE selected_course sc SET selected=false FROM course_item ci,template_item ti
WHERE sc.course_item_id=ci.id AND ci.requirement_id=ti.id AND sc.plan_id=$1 AND ti.template_id=$2
`

type DeselectTemplateChoicesParams struct {
	PlanID     uuid.UUID
	TemplateID uuid.UUID
}

func (q *Queries) DeselectTemplateChoices(ctx context.Context, arg DeselectTemplateChoicesParams) error {
	_, err := q.db.Exec(ctx, deselectTemplateChoices, arg.PlanID, arg.TemplateID)
	return err
}

const detachPlanTemplate = `-- name: DetachPlanTemplate :exec
DELETE FROM plan_template WHERE plan_id=$1 AND template_id=$2
`

type DetachPlanTemplateParams struct {
	PlanID     uuid.UUID
	TemplateID uuid.UUID
}

func (q *Queries) DetachPlanTemplate(ctx context.Context, arg DetachPlanTemplateParams) error {
	_, err := q.db.Exec(ctx, detachPlanTemplate, arg.PlanID, arg.TemplateID)
	return err
}

const fillFreeCourse = `-- name: FillFreeCourse :execrows
INSERT INTO free_course(id,user_id,course_item_id,filled_course_id)
SELECT $1,$2,$3,c.id FROM course c WHERE c.id=$4
ON CONFLICT(course_item_id,user_id) DO UPDATE SET filled_course_id=excluded.filled_course_id
`

type FillFreeCourseParams struct {
	ID           uuid.UUID
	UserID       string
	CourseItemID uuid.UUID
	CourseID     uuid.UUID
}

func (q *Queries) FillFreeCourse(ctx context.Context, arg FillFreeCourseParams) (int64, error) {
	result, err := q.db.Exec(ctx, fillFreeCourse,
		arg.ID,
		arg.UserID,
		arg.CourseItemID,
		arg.CourseID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOwnedPlan = `-- name: GetOwnedPlan :one
SELECT id FROM plan WHERE user_id=$1
`

func (q *Queries) GetOwnedPlan(ctx context.Context, userID string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getOwnedPlan, userID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listPlanChoices = `-- name: ListPlanChoices :many
SELECT ci.id,ci.type,ci.course_id,fc.filled_course_id,
       COALESCE(sc.selected,false)::boolean AS selected
FROM plan p
JOIN plan_template pt ON pt.plan_id=p.id
JOIN template_item ti ON ti.template_id=pt.template_id
JOIN course_item ci ON ci.requirement_id=ti.id
LEFT JOIN selected_course sc ON sc.plan_id=p.id AND sc.course_item_id=ci.id
LEFT JOIN free_course fc ON fc.user_id=p.user_id AND fc.course_item_id=ci.id
WHERE p.id=$1 ORDER BY ci.id
`

type ListPlanChoicesRow struct {
	ID             uuid.UUID
	Type           CourseItemType
	CourseID       pgtype.UUID
	FilledCourseID pgtype.UUID
	Selected       bool
}

func (q *Queries) ListPlanChoices(ctx context.Context, id uuid.UUID) ([]ListPlanChoicesRow, error) {
	rows, err := q.db.Query(ctx, listPlanChoices, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlanChoicesRow{}
	for rows.Next() {
		var i ListPlanChoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.CourseID,
			&i.FilledCourseID,
			&i.Selected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanTemplateIDs = `-- name: ListPlanTemplateIDs :many
SELECT pt.template_id FROM plan_template pt JOIN template t ON t.id=pt.template_id WHERE pt.plan_id=$1 ORDER BY t.name,t.id
`

func (q *Queries) ListPlanTemplateIDs(ctx context.Context, planID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPlanTemplateIDs, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var template_id uuid.UUID
		if err := rows.Scan(&template_id); err != nil {
			return nil, err
		}
		items = append(items, template_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAvailableTemplate = `-- name: LockAvailableTemplate :one
SELECT id FROM template WHERE id=$1 FOR KEY SHARE
`

func (q *Queries) LockAvailableTemplate(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockAvailableTemplate, id)
	err := row.Scan(&id)
	return id, err
}

const lockPlanFreeCourseItem = `-- name: LockPlanFreeCourseItem :one
SELECT ci.id FROM plan_template pt
JOIN template_item ti ON ti.template_id=pt.template_id
JOIN course_item ci ON ci.requirement_id=ti.id
WHERE pt.plan_id=$1 AND ci.id=$2 AND ci.type='free' FOR KEY SHARE OF ci
`

type LockPlanFreeCourseItemParams struct {
	PlanID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) LockPlanFreeCourseItem(ctx context.Context, arg LockPlanFreeCourseItemParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockPlanFreeCourseItem, arg.PlanID, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const removeCourseFromPlanSchedules = `-- name: RemoveCourseFromPlanSchedules :exec
DELETE FROM schedule_course sc USING schedule s
WHERE sc.schedule_id=s.id AND s.plan_id=$1 AND sc.course_id=$2
`

type RemoveCourseFromPlanSchedulesParams struct {
	PlanID   uuid.UUID
	CourseID uuid.UUID
}

func (q *Queries) RemoveCourseFromPlanSchedules(ctx context.Context, arg RemoveCourseFromPlanSchedulesParams) error {
	_, err := q.db.Exec(ctx, removeCourseFromPlanSchedules, arg.PlanID, arg.CourseID)
	return err
}

const removeSelectedCourse = `-- name: RemoveSelectedCourse :exec
DELETE FROM selected_course sc USING course_item ci
LEFT JOIN free_course fc ON fc.course_item_id=ci.id AND fc.user_id=$1
WHERE sc.plan_id=$2 AND sc.course_item_id=ci.id
AND ((ci.type='fixed' AND ci.course_id=$3::uuid) OR (ci.type='free' AND fc.filled_course_id=$3::uuid))
`

type RemoveSelectedCourseParams struct {
	UserID   string
	PlanID   uuid.UUID
	CourseID uuid.UUID
}

func (q *Queries) RemoveSelectedCourse(ctx context.Context, arg RemoveSelectedCourseParams) error {
	_, err := q.db.Exec(ctx, removeSelectedCourse, arg.UserID, arg.PlanID, arg.CourseID)
	return err
}

const setPlanChoice = `-- name: SetPlanChoice :execrows
INSERT INTO selected_course(plan_id,course_item_id,selected)
SELECT pt.plan_id,ci.id,$1 FROM plan_template pt
JOIN template_item ti ON ti.template_id=pt.template_id
JOIN course_item ci ON ci.requirement_id=ti.id
WHERE pt.plan_id=$2 AND ci.id=$3
ON CONFLICT(plan_id,course_item_id) DO UPDATE SET selected=excluded.selected
`

type SetPlanChoiceParams struct {
	Selected     bool
	PlanID       uuid.UUID
	CourseItemID uuid.UUID
}

func (q *Queries) SetPlanChoice(ctx context.Context, arg SetPlanChoiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPlanChoice, arg.Selected, arg.PlanID, arg.CourseItemID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
