// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: selection.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachPlanTemplate = `-- name: AttachPlanTemplate :exec
INSERT INTO plan_template(plan_id,template_id) VALUES ($1,$2) ON CONFLICT DO NOTHING
`

type AttachPlanTemplateParams struct {
	PlanID     uuid.UUID
	TemplateID uuid.UUID
}

func (q *Queries) AttachPlanTemplate(ctx context.Context, arg AttachPlanTemplateParams) error {
	_, err := q.db.Exec(ctx, attachPlanTemplate, arg.PlanID, arg.TemplateID)
	return err
}

const deselectTemplateChoices = `-- name: DeselectTemplateChoices :exec
UPDATE selected_course sc SET selected=false FROM course_item ci,template_item ti
WHERE sc.course_item_id=ci.id AND ci.requirement_id=ti.id AND sc.plan_id=$1 AND ti.template_id=$2
`

type DeselectTemplateChoicesParams struct {
	PlanID     uuid.UUID
	TemplateID uuid.UUID
}

func (q *Queries) DeselectTemplateChoices(ctx context.Context, arg DeselectTemplateChoicesParams) error {
	_, err := q.db.Exec(ctx, deselectTemplateChoices, arg.PlanID, arg.TemplateID)
	return err
}

const detachPlanTemplate = `-- name: DetachPlanTemplate :exec
DELETE FROM plan_template WHERE plan_id=$1 AND template_id=$2
`

type DetachPlanTemplateParams struct {
	PlanID     uuid.UUID
	TemplateID uuid.UUID
}

func (q *Queries) DetachPlanTemplate(ctx context.Context, arg DetachPlanTemplateParams) error {
	_, err := q.db.Exec(ctx, detachPlanTemplate, arg.PlanID, arg.TemplateID)
	return err
}

const getOwnedPlan = `-- name: GetOwnedPlan :one
SELECT id FROM plan WHERE user_id=$1
`

func (q *Queries) GetOwnedPlan(ctx context.Context, userID string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getOwnedPlan, userID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listPlanChoices = `-- name: ListPlanChoices :many
SELECT ci.id,ci.type,ci.course_id,fc.filled_course_id,
       COALESCE(sc.selected,false)::boolean AS selected
FROM plan p
JOIN plan_template pt ON pt.plan_id=p.id
JOIN template_item ti ON ti.template_id=pt.template_id
JOIN course_item ci ON ci.requirement_id=ti.id
LEFT JOIN selected_course sc ON sc.plan_id=p.id AND sc.course_item_id=ci.id
LEFT JOIN free_course fc ON fc.user_id=p.user_id AND fc.course_item_id=ci.id
WHERE p.id=$1 ORDER BY ci.id
`

type ListPlanChoicesRow struct {
	ID             uuid.UUID
	Type           CourseItemType
	CourseID       pgtype.UUID
	FilledCourseID pgtype.UUID
	Selected       bool
}

func (q *Queries) ListPlanChoices(ctx context.Context, id uuid.UUID) ([]ListPlanChoicesRow, error) {
	rows, err := q.db.Query(ctx, listPlanChoices, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlanChoicesRow{}
	for rows.Next() {
		var i ListPlanChoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.CourseID,
			&i.FilledCourseID,
			&i.Selected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanTemplateIDs = `-- name: ListPlanTemplateIDs :many
SELECT pt.template_id FROM plan_template pt JOIN template t ON t.id=pt.template_id WHERE pt.plan_id=$1 ORDER BY t.name,t.id
`

func (q *Queries) ListPlanTemplateIDs(ctx context.Context, planID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPlanTemplateIDs, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var template_id uuid.UUID
		if err := rows.Scan(&template_id); err != nil {
			return nil, err
		}
		items = append(items, template_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAvailableTemplate = `-- name: LockAvailableTemplate :one
SELECT id FROM template WHERE id=$1 FOR KEY SHARE
`

func (q *Queries) LockAvailableTemplate(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockAvailableTemplate, id)
	err := row.Scan(&id)
	return id, err
}
