// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: template.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFixedTemplateCourse = `-- name: CreateFixedTemplateCourse :one
INSERT INTO course_item(id,requirement_id,type,course_id)
SELECT $1,$2,'fixed',c.id FROM course c WHERE c.code=$3 RETURNING id
`

type CreateFixedTemplateCourseParams struct {
	ID            uuid.UUID
	RequirementID uuid.UUID
	Code          string
}

func (q *Queries) CreateFixedTemplateCourse(ctx context.Context, arg CreateFixedTemplateCourseParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createFixedTemplateCourse, arg.ID, arg.RequirementID, arg.Code)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createFreeTemplateCourse = `-- name: CreateFreeTemplateCourse :exec
INSERT INTO course_item(id,requirement_id,type) VALUES($1,$2,'free')
`

type CreateFreeTemplateCourseParams struct {
	ID            uuid.UUID
	RequirementID uuid.UUID
}

func (q *Queries) CreateFreeTemplateCourse(ctx context.Context, arg CreateFreeTemplateCourseParams) error {
	_, err := q.db.Exec(ctx, createFreeTemplateCourse, arg.ID, arg.RequirementID)
	return err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO template(id,name,description,created_by) VALUES($1,$2,$3,$4) RETURNING id, name, description, created_by
`

type CreateTemplateParams struct {
	ID          uuid.UUID
	Name        string
	Description *string
	CreatedBy   *string
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
	)
	return i, err
}

const createTemplateItem = `-- name: CreateTemplateItem :exec
INSERT INTO template_item(id,template_id,type,description,order_index) VALUES($1,$2,$3,$4,$5)
`

type CreateTemplateItemParams struct {
	ID          uuid.UUID
	TemplateID  uuid.UUID
	Type        ItemType
	Description *string
	OrderIndex  int32
}

func (q *Queries) CreateTemplateItem(ctx context.Context, arg CreateTemplateItemParams) error {
	_, err := q.db.Exec(ctx, createTemplateItem,
		arg.ID,
		arg.TemplateID,
		arg.Type,
		arg.Description,
		arg.OrderIndex,
	)
	return err
}

const deleteManagedTemplate = `-- name: DeleteManagedTemplate :execrows
DELETE FROM template WHERE id=$1 AND (created_by=$2::text OR $3::boolean)
`

type DeleteManagedTemplateParams struct {
	ID      uuid.UUID
	ActorID string
	IsAdmin bool
}

func (q *Queries) DeleteManagedTemplate(ctx context.Context, arg DeleteManagedTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteManagedTemplate, arg.ID, arg.ActorID, arg.IsAdmin)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, name, description, created_by FROM template WHERE id=$1
`

func (q *Queries) GetTemplate(ctx context.Context, id uuid.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
	)
	return i, err
}

const listTemplateCourseItems = `-- name: ListTemplateCourseItems :many
SELECT ci.id,ci.requirement_id,ci.type,ci.course_id,c.code AS course_code FROM course_item ci
JOIN template_item ti ON ti.id=ci.requirement_id LEFT JOIN course c ON c.id=ci.course_id
WHERE ti.template_id=$1 ORDER BY ci.id
`

type ListTemplateCourseItemsRow struct {
	ID            uuid.UUID
	RequirementID uuid.UUID
	Type          CourseItemType
	CourseID      pgtype.UUID
	CourseCode    *string
}

func (q *Queries) ListTemplateCourseItems(ctx context.Context, templateID uuid.UUID) ([]ListTemplateCourseItemsRow, error) {
	rows, err := q.db.Query(ctx, listTemplateCourseItems, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTemplateCourseItemsRow{}
	for rows.Next() {
		var i ListTemplateCourseItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequirementID,
			&i.Type,
			&i.CourseID,
			&i.CourseCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateItems = `-- name: ListTemplateItems :many
SELECT id, template_id, type, description, order_index FROM template_item WHERE template_id=$1 ORDER BY order_index,id
`

func (q *Queries) ListTemplateItems(ctx context.Context, templateID uuid.UUID) ([]TemplateItem, error) {
	rows, err := q.db.Query(ctx, listTemplateItems, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplateItem{}
	for rows.Next() {
		var i TemplateItem
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Type,
			&i.Description,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, description, created_by FROM template WHERE NOT $1::boolean OR created_by=$2::text ORDER BY name
`

type ListTemplatesParams struct {
	OwnedOnly bool
	ActorID   string
}

func (q *Queries) ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates, arg.OwnedOnly, arg.ActorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameManagedTemplate = `-- name: RenameManagedTemplate :execrows
UPDATE template SET name=$1,description=$2
WHERE id=$3 AND (created_by=$4::text OR $5::boolean)
`

type RenameManagedTemplateParams struct {
	Name        string
	Description *string
	ID          uuid.UUID
	ActorID     string
	IsAdmin     bool
}

func (q *Queries) RenameManagedTemplate(ctx context.Context, arg RenameManagedTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameManagedTemplate,
		arg.Name,
		arg.Description,
		arg.ID,
		arg.ActorID,
		arg.IsAdmin,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
