// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createDefaultSchedule = `-- name: CreateDefaultSchedule :exec
INSERT INTO schedule(id,name,plan_id) VALUES ($1,$2,$3)
`

type CreateDefaultScheduleParams struct {
	ID     uuid.UUID
	Name   string
	PlanID uuid.UUID
}

func (q *Queries) CreateDefaultSchedule(ctx context.Context, arg CreateDefaultScheduleParams) error {
	_, err := q.db.Exec(ctx, createDefaultSchedule, arg.ID, arg.Name, arg.PlanID)
	return err
}

const createDefaultTermRange = `-- name: CreateDefaultTermRange :exec
INSERT INTO user_term_range(user_id,start_term,start_year,end_term,end_year) VALUES ($1,$2,$3,$4,$5)
`

type CreateDefaultTermRangeParams struct {
	UserID    string
	StartTerm Season
	StartYear int32
	EndTerm   Season
	EndYear   int32
}

func (q *Queries) CreateDefaultTermRange(ctx context.Context, arg CreateDefaultTermRangeParams) error {
	_, err := q.db.Exec(ctx, createDefaultTermRange,
		arg.UserID,
		arg.StartTerm,
		arg.StartYear,
		arg.EndTerm,
		arg.EndYear,
	)
	return err
}

const createPlan = `-- name: CreatePlan :exec
INSERT INTO plan(id,user_id) VALUES ($1,$2)
`

type CreatePlanParams struct {
	ID     uuid.UUID
	UserID string
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) error {
	_, err := q.db.Exec(ctx, createPlan, arg.ID, arg.UserID)
	return err
}

const createProviderAccount = `-- name: CreateProviderAccount :exec
INSERT INTO account(user_id,type,provider,provider_account_id) VALUES ($1,'oauth',$2,$3)
`

type CreateProviderAccountParams struct {
	UserID            string
	Provider          string
	ProviderAccountID string
}

func (q *Queries) CreateProviderAccount(ctx context.Context, arg CreateProviderAccountParams) error {
	_, err := q.db.Exec(ctx, createProviderAccount, arg.UserID, arg.Provider, arg.ProviderAccountID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "user"(id,email,name,image) VALUES ($1,$2,$3,$4) RETURNING id,email,name,image,role
`

type CreateUserParams struct {
	ID    string
	Email string
	Name  *string
	Image *string
}

type CreateUserRow struct {
	ID    string
	Email string
	Name  *string
	Image *string
	Role  RoleType
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Image,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.Role,
	)
	return i, err
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS(SELECT 1 FROM "user" WHERE lower(email)=lower($1::text))
`

func (q *Queries) EmailExists(ctx context.Context, dollar_1 string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, dollar_1)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getProviderUser = `-- name: GetProviderUser :one
SELECT u.id, u.email, u.name, u.image, u.role FROM "user" u JOIN account a ON a.user_id=u.id WHERE a.provider=$1 AND a.provider_account_id=$2
`

type GetProviderUserParams struct {
	Provider          string
	ProviderAccountID string
}

type GetProviderUserRow struct {
	ID    string
	Email string
	Name  *string
	Image *string
	Role  RoleType
}

func (q *Queries) GetProviderUser(ctx context.Context, arg GetProviderUserParams) (GetProviderUserRow, error) {
	row := q.db.QueryRow(ctx, getProviderUser, arg.Provider, arg.ProviderAccountID)
	var i GetProviderUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.Role,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, image, role FROM "user" WHERE id=$1
`

type GetUserRow struct {
	ID    string
	Email string
	Name  *string
	Image *string
	Role  RoleType
}

func (q *Queries) GetUser(ctx context.Context, id string) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.Role,
	)
	return i, err
}

const lockIdentity = `-- name: LockIdentity :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text,0))
`

func (q *Queries) LockIdentity(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockIdentity, dollar_1)
	return err
}
