// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package catalog

import (
	"context"

	"github.com/pl3lee/uwplan/api/internal/domain/course"
	mock "github.com/stretchr/testify/mock"
)

// NewCourseGatewayMock creates a new instance of CourseGatewayMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseGatewayMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseGatewayMock {
	mock := &CourseGatewayMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CourseGatewayMock is an autogenerated mock type for the CourseGateway type
type CourseGatewayMock struct {
	mock.Mock
}

type CourseGatewayMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CourseGatewayMock) EXPECT() *CourseGatewayMock_Expecter {
	return &CourseGatewayMock_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type CourseGatewayMock
func (_mock *CourseGatewayMock) Fetch(context1 context.Context) (course.Import, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 course.Import
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (course.Import, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) course.Import); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(course.Import)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CourseGatewayMock_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type CourseGatewayMock_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - context1 context.Context
func (_e *CourseGatewayMock_Expecter) Fetch(context1 interface{}) *CourseGatewayMock_Fetch_Call {
	return &CourseGatewayMock_Fetch_Call{Call: _e.mock.On("Fetch", context1)}
}

func (_c *CourseGatewayMock_Fetch_Call) Run(run func(context1 context.Context)) *CourseGatewayMock_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CourseGatewayMock_Fetch_Call) Return(importParam course.Import, err error) *CourseGatewayMock_Fetch_Call {
	_c.Call.Return(importParam, err)
	return _c
}

func (_c *CourseGatewayMock_Fetch_Call) RunAndReturn(run func(context1 context.Context) (course.Import, error)) *CourseGatewayMock_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// NewCourseRepositoryMock creates a new instance of CourseRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseRepositoryMock {
	mock := &CourseRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CourseRepositoryMock is an autogenerated mock type for the CourseRepository type
type CourseRepositoryMock struct {
	mock.Mock
}

type CourseRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CourseRepositoryMock) EXPECT() *CourseRepositoryMock_Expecter {
	return &CourseRepositoryMock_Expecter{mock: &_m.Mock}
}

// Import provides a mock function for the type CourseRepositoryMock
func (_mock *CourseRepositoryMock) Import(context1 context.Context, importParam course.Import) error {
	ret := _mock.Called(context1, importParam)

	if len(ret) == 0 {
		panic("no return value specified for Import")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, course.Import) error); ok {
		r0 = returnFunc(context1, importParam)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CourseRepositoryMock_Import_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Import'
type CourseRepositoryMock_Import_Call struct {
	*mock.Call
}

// Import is a helper method to define mock.On call
//   - context1 context.Context
//   - importParam course.Import
func (_e *CourseRepositoryMock_Expecter) Import(context1 interface{}, importParam interface{}) *CourseRepositoryMock_Import_Call {
	return &CourseRepositoryMock_Import_Call{Call: _e.mock.On("Import", context1, importParam)}
}

func (_c *CourseRepositoryMock_Import_Call) Run(run func(context1 context.Context, importParam course.Import)) *CourseRepositoryMock_Import_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 course.Import
		if args[1] != nil {
			arg1 = args[1].(course.Import)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CourseRepositoryMock_Import_Call) Return(err error) *CourseRepositoryMock_Import_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CourseRepositoryMock_Import_Call) RunAndReturn(run func(context1 context.Context, importParam course.Import) error) *CourseRepositoryMock_Import_Call {
	_c.Call.Return(run)
	return _c
}
