// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package seed

import (
	"context"

	"github.com/pl3lee/uwplan/api/internal/domain/template"
	mock "github.com/stretchr/testify/mock"
)

// NewTemplateGatewayMock creates a new instance of TemplateGatewayMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTemplateGatewayMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TemplateGatewayMock {
	mock := &TemplateGatewayMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TemplateGatewayMock is an autogenerated mock type for the TemplateGateway type
type TemplateGatewayMock struct {
	mock.Mock
}

type TemplateGatewayMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TemplateGatewayMock) EXPECT() *TemplateGatewayMock_Expecter {
	return &TemplateGatewayMock_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type TemplateGatewayMock
func (_mock *TemplateGatewayMock) Fetch(context1 context.Context) (template.Seed, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 template.Seed
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (template.Seed, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) template.Seed); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(template.Seed)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TemplateGatewayMock_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type TemplateGatewayMock_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - context1 context.Context
func (_e *TemplateGatewayMock_Expecter) Fetch(context1 interface{}) *TemplateGatewayMock_Fetch_Call {
	return &TemplateGatewayMock_Fetch_Call{Call: _e.mock.On("Fetch", context1)}
}

func (_c *TemplateGatewayMock_Fetch_Call) Run(run func(context1 context.Context)) *TemplateGatewayMock_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TemplateGatewayMock_Fetch_Call) Return(seed template.Seed, err error) *TemplateGatewayMock_Fetch_Call {
	_c.Call.Return(seed, err)
	return _c
}

func (_c *TemplateGatewayMock_Fetch_Call) RunAndReturn(run func(context1 context.Context) (template.Seed, error)) *TemplateGatewayMock_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// NewTemplateRepositoryMock creates a new instance of TemplateRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTemplateRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TemplateRepositoryMock {
	mock := &TemplateRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TemplateRepositoryMock is an autogenerated mock type for the TemplateRepository type
type TemplateRepositoryMock struct {
	mock.Mock
}

type TemplateRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TemplateRepositoryMock) EXPECT() *TemplateRepositoryMock_Expecter {
	return &TemplateRepositoryMock_Expecter{mock: &_m.Mock}
}

// Seed provides a mock function for the type TemplateRepositoryMock
func (_mock *TemplateRepositoryMock) Seed(context1 context.Context, seed template.Seed) (template.SeedResult, error) {
	ret := _mock.Called(context1, seed)

	if len(ret) == 0 {
		panic("no return value specified for Seed")
	}

	var r0 template.SeedResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, template.Seed) (template.SeedResult, error)); ok {
		return returnFunc(context1, seed)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, template.Seed) template.SeedResult); ok {
		r0 = returnFunc(context1, seed)
	} else {
		r0 = ret.Get(0).(template.SeedResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, template.Seed) error); ok {
		r1 = returnFunc(context1, seed)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TemplateRepositoryMock_Seed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seed'
type TemplateRepositoryMock_Seed_Call struct {
	*mock.Call
}

// Seed is a helper method to define mock.On call
//   - context1 context.Context
//   - seed template.Seed
func (_e *TemplateRepositoryMock_Expecter) Seed(context1 interface{}, seed interface{}) *TemplateRepositoryMock_Seed_Call {
	return &TemplateRepositoryMock_Seed_Call{Call: _e.mock.On("Seed", context1, seed)}
}

func (_c *TemplateRepositoryMock_Seed_Call) Run(run func(context1 context.Context, seed template.Seed)) *TemplateRepositoryMock_Seed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 template.Seed
		if args[1] != nil {
			arg1 = args[1].(template.Seed)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TemplateRepositoryMock_Seed_Call) Return(seedResult template.SeedResult, err error) *TemplateRepositoryMock_Seed_Call {
	_c.Call.Return(seedResult, err)
	return _c
}

func (_c *TemplateRepositoryMock_Seed_Call) RunAndReturn(run func(context1 context.Context, seed template.Seed) (template.SeedResult, error)) *TemplateRepositoryMock_Seed_Call {
	_c.Call.Return(run)
	return _c
}
