// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package course

import (
	"context"

	"github.com/pl3lee/uwplan/api/internal/domain/course"
	mock "github.com/stretchr/testify/mock"
)

// NewCourseRepositoryMock creates a new instance of CourseRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseRepositoryMock {
	mock := &CourseRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CourseRepositoryMock is an autogenerated mock type for the CourseRepository type
type CourseRepositoryMock struct {
	mock.Mock
}

type CourseRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CourseRepositoryMock) EXPECT() *CourseRepositoryMock_Expecter {
	return &CourseRepositoryMock_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type CourseRepositoryMock
func (_mock *CourseRepositoryMock) List(context1 context.Context) ([]course.Course, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []course.Course
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]course.Course, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []course.Course); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]course.Course)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CourseRepositoryMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type CourseRepositoryMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
func (_e *CourseRepositoryMock_Expecter) List(context1 interface{}) *CourseRepositoryMock_List_Call {
	return &CourseRepositoryMock_List_Call{Call: _e.mock.On("List", context1)}
}

func (_c *CourseRepositoryMock_List_Call) Run(run func(context1 context.Context)) *CourseRepositoryMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CourseRepositoryMock_List_Call) Return(courses []course.Course, err error) *CourseRepositoryMock_List_Call {
	_c.Call.Return(courses, err)
	return _c
}

func (_c *CourseRepositoryMock_List_Call) RunAndReturn(run func(context1 context.Context) ([]course.Course, error)) *CourseRepositoryMock_List_Call {
	_c.Call.Return(run)
	return _c
}
