// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package admin

import (
	"context"

	"github.com/pl3lee/uwplan/api/internal/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// NewUserRepositoryMock creates a new instance of UserRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepositoryMock {
	mock := &UserRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRepositoryMock is an autogenerated mock type for the UserRepository type
type UserRepositoryMock struct {
	mock.Mock
}

type UserRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepositoryMock) EXPECT() *UserRepositoryMock_Expecter {
	return &UserRepositoryMock_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type UserRepositoryMock
func (_mock *UserRepositoryMock) List(context1 context.Context) ([]user.User, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]user.User, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []user.User); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepositoryMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type UserRepositoryMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
func (_e *UserRepositoryMock_Expecter) List(context1 interface{}) *UserRepositoryMock_List_Call {
	return &UserRepositoryMock_List_Call{Call: _e.mock.On("List", context1)}
}

func (_c *UserRepositoryMock_List_Call) Run(run func(context1 context.Context)) *UserRepositoryMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserRepositoryMock_List_Call) Return(users []user.User, err error) *UserRepositoryMock_List_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *UserRepositoryMock_List_Call) RunAndReturn(run func(context1 context.Context) ([]user.User, error)) *UserRepositoryMock_List_Call {
	_c.Call.Return(run)
	return _c
}
