// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package selection

import (
	"context"

	"github.com/pl3lee/uwplan/api/internal/domain/selection"
	"github.com/pl3lee/uwplan/api/internal/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// NewSelectionRepositoryMock creates a new instance of SelectionRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSelectionRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SelectionRepositoryMock {
	mock := &SelectionRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SelectionRepositoryMock is an autogenerated mock type for the SelectionRepository type
type SelectionRepositoryMock struct {
	mock.Mock
}

type SelectionRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SelectionRepositoryMock) EXPECT() *SelectionRepositoryMock_Expecter {
	return &SelectionRepositoryMock_Expecter{mock: &_m.Mock}
}

// ChangeFreeCourse provides a mock function for the type SelectionRepositoryMock
func (_mock *SelectionRepositoryMock) ChangeFreeCourse(context1 context.Context, freeCourseChange selection.FreeCourseChange) error {
	ret := _mock.Called(context1, freeCourseChange)

	if len(ret) == 0 {
		panic("no return value specified for ChangeFreeCourse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, selection.FreeCourseChange) error); ok {
		r0 = returnFunc(context1, freeCourseChange)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SelectionRepositoryMock_ChangeFreeCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeFreeCourse'
type SelectionRepositoryMock_ChangeFreeCourse_Call struct {
	*mock.Call
}

// ChangeFreeCourse is a helper method to define mock.On call
//   - context1 context.Context
//   - freeCourseChange selection.FreeCourseChange
func (_e *SelectionRepositoryMock_Expecter) ChangeFreeCourse(context1 interface{}, freeCourseChange interface{}) *SelectionRepositoryMock_ChangeFreeCourse_Call {
	return &SelectionRepositoryMock_ChangeFreeCourse_Call{Call: _e.mock.On("ChangeFreeCourse", context1, freeCourseChange)}
}

func (_c *SelectionRepositoryMock_ChangeFreeCourse_Call) Run(run func(context1 context.Context, freeCourseChange selection.FreeCourseChange)) *SelectionRepositoryMock_ChangeFreeCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 selection.FreeCourseChange
		if args[1] != nil {
			arg1 = args[1].(selection.FreeCourseChange)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SelectionRepositoryMock_ChangeFreeCourse_Call) Return(err error) *SelectionRepositoryMock_ChangeFreeCourse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SelectionRepositoryMock_ChangeFreeCourse_Call) RunAndReturn(run func(context1 context.Context, freeCourseChange selection.FreeCourseChange) error) *SelectionRepositoryMock_ChangeFreeCourse_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveCourse provides a mock function for the type SelectionRepositoryMock
func (_mock *SelectionRepositoryMock) RemoveCourse(context1 context.Context, removal selection.Removal) error {
	ret := _mock.Called(context1, removal)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCourse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, selection.Removal) error); ok {
		r0 = returnFunc(context1, removal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SelectionRepositoryMock_RemoveCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveCourse'
type SelectionRepositoryMock_RemoveCourse_Call struct {
	*mock.Call
}

// RemoveCourse is a helper method to define mock.On call
//   - context1 context.Context
//   - removal selection.Removal
func (_e *SelectionRepositoryMock_Expecter) RemoveCourse(context1 interface{}, removal interface{}) *SelectionRepositoryMock_RemoveCourse_Call {
	return &SelectionRepositoryMock_RemoveCourse_Call{Call: _e.mock.On("RemoveCourse", context1, removal)}
}

func (_c *SelectionRepositoryMock_RemoveCourse_Call) Run(run func(context1 context.Context, removal selection.Removal)) *SelectionRepositoryMock_RemoveCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 selection.Removal
		if args[1] != nil {
			arg1 = args[1].(selection.Removal)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SelectionRepositoryMock_RemoveCourse_Call) Return(err error) *SelectionRepositoryMock_RemoveCourse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SelectionRepositoryMock_RemoveCourse_Call) RunAndReturn(run func(context1 context.Context, removal selection.Removal) error) *SelectionRepositoryMock_RemoveCourse_Call {
	_c.Call.Return(run)
	return _c
}

// SetChoice provides a mock function for the type SelectionRepositoryMock
func (_mock *SelectionRepositoryMock) SetChoice(context1 context.Context, toggle selection.Toggle) error {
	ret := _mock.Called(context1, toggle)

	if len(ret) == 0 {
		panic("no return value specified for SetChoice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, selection.Toggle) error); ok {
		r0 = returnFunc(context1, toggle)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SelectionRepositoryMock_SetChoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetChoice'
type SelectionRepositoryMock_SetChoice_Call struct {
	*mock.Call
}

// SetChoice is a helper method to define mock.On call
//   - context1 context.Context
//   - toggle selection.Toggle
func (_e *SelectionRepositoryMock_Expecter) SetChoice(context1 interface{}, toggle interface{}) *SelectionRepositoryMock_SetChoice_Call {
	return &SelectionRepositoryMock_SetChoice_Call{Call: _e.mock.On("SetChoice", context1, toggle)}
}

func (_c *SelectionRepositoryMock_SetChoice_Call) Run(run func(context1 context.Context, toggle selection.Toggle)) *SelectionRepositoryMock_SetChoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 selection.Toggle
		if args[1] != nil {
			arg1 = args[1].(selection.Toggle)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SelectionRepositoryMock_SetChoice_Call) Return(err error) *SelectionRepositoryMock_SetChoice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SelectionRepositoryMock_SetChoice_Call) RunAndReturn(run func(context1 context.Context, toggle selection.Toggle) error) *SelectionRepositoryMock_SetChoice_Call {
	_c.Call.Return(run)
	return _c
}

// SetTemplate provides a mock function for the type SelectionRepositoryMock
func (_mock *SelectionRepositoryMock) SetTemplate(context1 context.Context, membership selection.Membership) error {
	ret := _mock.Called(context1, membership)

	if len(ret) == 0 {
		panic("no return value specified for SetTemplate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, selection.Membership) error); ok {
		r0 = returnFunc(context1, membership)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SelectionRepositoryMock_SetTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTemplate'
type SelectionRepositoryMock_SetTemplate_Call struct {
	*mock.Call
}

// SetTemplate is a helper method to define mock.On call
//   - context1 context.Context
//   - membership selection.Membership
func (_e *SelectionRepositoryMock_Expecter) SetTemplate(context1 interface{}, membership interface{}) *SelectionRepositoryMock_SetTemplate_Call {
	return &SelectionRepositoryMock_SetTemplate_Call{Call: _e.mock.On("SetTemplate", context1, membership)}
}

func (_c *SelectionRepositoryMock_SetTemplate_Call) Run(run func(context1 context.Context, membership selection.Membership)) *SelectionRepositoryMock_SetTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 selection.Membership
		if args[1] != nil {
			arg1 = args[1].(selection.Membership)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SelectionRepositoryMock_SetTemplate_Call) Return(err error) *SelectionRepositoryMock_SetTemplate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SelectionRepositoryMock_SetTemplate_Call) RunAndReturn(run func(context1 context.Context, membership selection.Membership) error) *SelectionRepositoryMock_SetTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function for the type SelectionRepositoryMock
func (_mock *SelectionRepositoryMock) State(context1 context.Context, user1 user.User) (selection.State, error) {
	ret := _mock.Called(context1, user1)

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 selection.State
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) (selection.State, error)); ok {
		return returnFunc(context1, user1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) selection.State); ok {
		r0 = returnFunc(context1, user1)
	} else {
		r0 = ret.Get(0).(selection.State)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.User) error); ok {
		r1 = returnFunc(context1, user1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SelectionRepositoryMock_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type SelectionRepositoryMock_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
//   - context1 context.Context
//   - user1 user.User
func (_e *SelectionRepositoryMock_Expecter) State(context1 interface{}, user1 interface{}) *SelectionRepositoryMock_State_Call {
	return &SelectionRepositoryMock_State_Call{Call: _e.mock.On("State", context1, user1)}
}

func (_c *SelectionRepositoryMock_State_Call) Run(run func(context1 context.Context, user1 user.User)) *SelectionRepositoryMock_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.User
		if args[1] != nil {
			arg1 = args[1].(user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SelectionRepositoryMock_State_Call) Return(state selection.State, err error) *SelectionRepositoryMock_State_Call {
	_c.Call.Return(state, err)
	return _c
}

func (_c *SelectionRepositoryMock_State_Call) RunAndReturn(run func(context1 context.Context, user1 user.User) (selection.State, error)) *SelectionRepositoryMock_State_Call {
	_c.Call.Return(run)
	return _c
}
