// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package user

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID         uuid.UUID
	ProviderID string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Email      string
	Name       string
}

type UserSession struct {
	ID        string
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
}
