// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	"github.com/pl3lee/uwplan/api/internal/domain/session"
	"github.com/pl3lee/uwplan/api/internal/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// NewUserRepositoryMock creates a new instance of UserRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepositoryMock {
	mock := &UserRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRepositoryMock is an autogenerated mock type for the UserRepository type
type UserRepositoryMock struct {
	mock.Mock
}

type UserRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepositoryMock) EXPECT() *UserRepositoryMock_Expecter {
	return &UserRepositoryMock_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function for the type UserRepositoryMock
func (_mock *UserRepositoryMock) GetUser(context1 context.Context, user1 user.User) (user.User, error) {
	ret := _mock.Called(context1, user1)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) (user.User, error)); ok {
		return returnFunc(context1, user1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) user.User); ok {
		r0 = returnFunc(context1, user1)
	} else {
		r0 = ret.Get(0).(user.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.User) error); ok {
		r1 = returnFunc(context1, user1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepositoryMock_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type UserRepositoryMock_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - context1 context.Context
//   - user1 user.User
func (_e *UserRepositoryMock_Expecter) GetUser(context1 interface{}, user1 interface{}) *UserRepositoryMock_GetUser_Call {
	return &UserRepositoryMock_GetUser_Call{Call: _e.mock.On("GetUser", context1, user1)}
}

func (_c *UserRepositoryMock_GetUser_Call) Run(run func(context1 context.Context, user1 user.User)) *UserRepositoryMock_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.User
		if args[1] != nil {
			arg1 = args[1].(user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepositoryMock_GetUser_Call) Return(user11 user.User, err error) *UserRepositoryMock_GetUser_Call {
	_c.Call.Return(user11, err)
	return _c
}

func (_c *UserRepositoryMock_GetUser_Call) RunAndReturn(run func(context1 context.Context, user1 user.User) (user.User, error)) *UserRepositoryMock_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveAccount provides a mock function for the type UserRepositoryMock
func (_mock *UserRepositoryMock) ResolveAccount(context1 context.Context, provisioning user.Provisioning) (user.User, error) {
	ret := _mock.Called(context1, provisioning)

	if len(ret) == 0 {
		panic("no return value specified for ResolveAccount")
	}

	var r0 user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.Provisioning) (user.User, error)); ok {
		return returnFunc(context1, provisioning)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.Provisioning) user.User); ok {
		r0 = returnFunc(context1, provisioning)
	} else {
		r0 = ret.Get(0).(user.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.Provisioning) error); ok {
		r1 = returnFunc(context1, provisioning)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepositoryMock_ResolveAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveAccount'
type UserRepositoryMock_ResolveAccount_Call struct {
	*mock.Call
}

// ResolveAccount is a helper method to define mock.On call
//   - context1 context.Context
//   - provisioning user.Provisioning
func (_e *UserRepositoryMock_Expecter) ResolveAccount(context1 interface{}, provisioning interface{}) *UserRepositoryMock_ResolveAccount_Call {
	return &UserRepositoryMock_ResolveAccount_Call{Call: _e.mock.On("ResolveAccount", context1, provisioning)}
}

func (_c *UserRepositoryMock_ResolveAccount_Call) Run(run func(context1 context.Context, provisioning user.Provisioning)) *UserRepositoryMock_ResolveAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.Provisioning
		if args[1] != nil {
			arg1 = args[1].(user.Provisioning)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepositoryMock_ResolveAccount_Call) Return(user1 user.User, err error) *UserRepositoryMock_ResolveAccount_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserRepositoryMock_ResolveAccount_Call) RunAndReturn(run func(context1 context.Context, provisioning user.Provisioning) (user.User, error)) *UserRepositoryMock_ResolveAccount_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionRepositoryMock creates a new instance of SessionRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepositoryMock {
	mock := &SessionRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionRepositoryMock is an autogenerated mock type for the SessionRepository type
type SessionRepositoryMock struct {
	mock.Mock
}

type SessionRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepositoryMock) EXPECT() *SessionRepositoryMock_Expecter {
	return &SessionRepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type SessionRepositoryMock
func (_mock *SessionRepositoryMock) Create(context1 context.Context, session1 session.Session) error {
	ret := _mock.Called(context1, session1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.Session) error); ok {
		r0 = returnFunc(context1, session1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SessionRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - session1 session.Session
func (_e *SessionRepositoryMock_Expecter) Create(context1 interface{}, session1 interface{}) *SessionRepositoryMock_Create_Call {
	return &SessionRepositoryMock_Create_Call{Call: _e.mock.On("Create", context1, session1)}
}

func (_c *SessionRepositoryMock_Create_Call) Run(run func(context1 context.Context, session1 session.Session)) *SessionRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 session.Session
		if args[1] != nil {
			arg1 = args[1].(session.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepositoryMock_Create_Call) Return(err error) *SessionRepositoryMock_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepositoryMock_Create_Call) RunAndReturn(run func(context1 context.Context, session1 session.Session) error) *SessionRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type SessionRepositoryMock
func (_mock *SessionRepositoryMock) Get(context1 context.Context, session1 session.Session) (session.Session, error) {
	ret := _mock.Called(context1, session1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 session.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.Session) (session.Session, error)); ok {
		return returnFunc(context1, session1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.Session) session.Session); ok {
		r0 = returnFunc(context1, session1)
	} else {
		r0 = ret.Get(0).(session.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, session.Session) error); ok {
		r1 = returnFunc(context1, session1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepositoryMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SessionRepositoryMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - session1 session.Session
func (_e *SessionRepositoryMock_Expecter) Get(context1 interface{}, session1 interface{}) *SessionRepositoryMock_Get_Call {
	return &SessionRepositoryMock_Get_Call{Call: _e.mock.On("Get", context1, session1)}
}

func (_c *SessionRepositoryMock_Get_Call) Run(run func(context1 context.Context, session1 session.Session)) *SessionRepositoryMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 session.Session
		if args[1] != nil {
			arg1 = args[1].(session.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepositoryMock_Get_Call) Return(session11 session.Session, err error) *SessionRepositoryMock_Get_Call {
	_c.Call.Return(session11, err)
	return _c
}

func (_c *SessionRepositoryMock_Get_Call) RunAndReturn(run func(context1 context.Context, session1 session.Session) (session.Session, error)) *SessionRepositoryMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type SessionRepositoryMock
func (_mock *SessionRepositoryMock) Revoke(context1 context.Context, session1 session.Session) error {
	ret := _mock.Called(context1, session1)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.Session) error); ok {
		r0 = returnFunc(context1, session1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepositoryMock_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type SessionRepositoryMock_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - context1 context.Context
//   - session1 session.Session
func (_e *SessionRepositoryMock_Expecter) Revoke(context1 interface{}, session1 interface{}) *SessionRepositoryMock_Revoke_Call {
	return &SessionRepositoryMock_Revoke_Call{Call: _e.mock.On("Revoke", context1, session1)}
}

func (_c *SessionRepositoryMock_Revoke_Call) Run(run func(context1 context.Context, session1 session.Session)) *SessionRepositoryMock_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 session.Session
		if args[1] != nil {
			arg1 = args[1].(session.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepositoryMock_Revoke_Call) Return(err error) *SessionRepositoryMock_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepositoryMock_Revoke_Call) RunAndReturn(run func(context1 context.Context, session1 session.Session) error) *SessionRepositoryMock_Revoke_Call {
	_c.Call.Return(run)
	return _c
}
