all: false
dir: '{{.InterfaceDir}}'
filename: mock.go
force-file-write: true
formatter: goimports
pkgname: '{{.SrcPackageName}}'
structname: '{{.InterfaceName}}Mock'
template: testify
packages:
  github.com/pl3lee/uwplan/api/internal/service/course:
    config:
      all: true
  github.com/pl3lee/uwplan/api/internal/service/schedule:
    config:
      all: true
  github.com/pl3lee/uwplan/api/internal/service/auth:
    config:
      all: true
  github.com/pl3lee/uwplan/api/internal/api:
    config:
      all: true
  github.com/pl3lee/uwplan/api/internal/service/oauth:
    config:
      all: true
